live-editing/services/DependencyResolver.ts

This PR fixes StackBlitz on prod (#396), but does not close any issues because further investigation is needed.
PR info:
- Added `@types/hammerjs` package. Related to #396. We are not closing this issue, we'll do further research why this package is needed in 6.0.1 but not in 6.0.0
- Added `immeadiate` package. Related to #234. We're not closing this issue as well. This is needed in all grid samples from 6.0.1 on. In 6.0.0 we needed it in Excel/CSV exporting where it is separately added.. It is suspected `jszip` library is not correctly imported in `igniteui-angular` package.

Update live editing packages

---

live-editing/configs/GridConfigGenerator.ts

Adding the IgxAvatarModule in the imports in the GridConfigGenerator.ts file.
Closes #503

Adding the missing IgxAvatarModule module

---

src/app/chip/chip.component.scss

fix(samples): Fix dragging chip selects all the text in StackBlitz

---

src/app/tabs/tabs-sample-4/components/tabs-sample-4.component.html
src/app/tabs/tabs-sample-4/components/tabs-sample-4.component.ts

1. Open first routing sample in IE and expect tabs - labels are missing - now are fixed 
2. Tabs labels are not longer underlined
Related to IgniteUI/igniteui-angular#1957

docs(tabs): Fixed styling issues, IE issue with missing labels #622

---

src/app/theming/dark-theme-sample/dark-theme-sample.component.html
src/app/theming/default-theme-sample/default-theme-sample.component.html
src/app/theming/styles/dark-theme-class.scss
src/app/theming/styles/dark-theme.scss
src/app/theming/styles/theme-classes.scss
src/app/theming/styles/themes.scss
src/app/theming/theme-chooser/theme-chooser-sample.component.html

After we've added the outlet directive we haven't added a calendar theme to the sample. This code change adds such team, and now if you go ahead and open any calendar (cell editing or Filtering) it should be with the same color of the theme.

Add theming for calendar

---

src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.html
src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.scss
src/app/financial-chart/multiple-feeds/financial-chart-multiple-feeds.component.html
src/app/financial-chart/multiple-feeds/financial-chart-multiple-feeds.component.scss
src/app/financial-chart/multiple-feeds/financial-chart-multiple-feeds.component.ts
src/app/financial-chart/services/financial-data.service.ts
src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.html
src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.scss
src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.ts

- toolbars are hidden in 2 marketing FC samples
- centered legend below charts
- corrected MS name
packages are not changed and we are still using v18.1

fixed chart samples per Jason's request

---

src/app/app-routing.module.ts

Tabs routing samples are removed from SB navigation tree because they are used only in stackbliz separate apps.
Related to #668

docs(tabs): Removing tabs routing samples from navigation tree #668

---

gulpfile.js

Since the generate-live-editing task ends up running some product code, temporarily implementing this workaround so we can push the samples.

adding navigator since our samples are currently running product code

---

src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.html
src/app/tree-grid/tree-grid-primaryforeignkey-sample/tree-grid-primaryforeignkey-sample.component.html
src/app/tree-grid/tree-grid-row-edit/tree-grid-row-editing-sample.component.html

Adding explicit width to tree grid samples for proper render in IE 11.

---

src/app/interactions/toggle/toggle.component.ts

We have toggle button and it is not compatible with close on outside click. This is why I changed the `closeOnOutsideClick` from `true` to `false`.

Set close on outside click to false

---

src/app/data-entries/select/select-sample-1/select-sample-1.component.ts

Use less items instead of setting more sample height to position the first/last selected items correctly for the illustration purposes.

fix(igxSelect): Better items positioning illustration( with less items)

---

src/app/layouts/card/card-sample-1/card-sample-1.component.scss

The card-sample-1.component.ts is used inside of a couple of overlay examples. It needs to have display:block. Otherwise, the overlay animations do no properly play when showing or hiding the component

chore(card): Add display:block to Card Sample 1 host

---

live-editing/configs/GeoMapConfigGenerator.ts
live-editing/configs/SparklineConfigGenerator.ts
live-editing/configs/core/BaseConfigGenerator.ts

Closes #1253 
This PR fixes:
- BaseConfigGenerator to import data **services**
- Rename **dataSource** to services, because we if use a dataSource that is **non-injectable** , we can just add it as an additional file. The service must be added to the providers in app-module.ts
- Rename `dataPaths` to additionalFilePaths, because we can add additional files that are not data sources (for example: another component, that we need as for our sample)
- Remove all data sources that are **non-injectable** (these are in GeoMapConfigGenerator and SparklineConfigGenerator)
- Replace FinancialChartModule with SparklineModule in SparklineConfigGenerator

Fix BaseConfigGenerator providers imports and configure Sparkline and GeoMap configs

---

live-editing/configs/ZoomSliderConfigGenerator.ts
src/app/charts/data-chart/SampleScatterStats.ts
src/app/charts/zoomslider/zoomslider-overview/zoomslider-overview.component.html
src/app/charts/zoomslider/zoomslider-overview/zoomslider-overview.component.scss
src/app/charts/zoomslider/zoomslider-overview/zoomslider-overview.component.ts
src/app/charts/zoomslider/zoomslider-samples.module.ts

- fixed overlay of zoomSlider over (zoom) DataChart
- fixed y-Axis range in main DataChart
- replaced Financial Price Series with Scatter Bubble Series to distinguish this sample from built-in zoomSlider in FinancialChart
- replaced data source based on requirements of Scatter Bubble Series
- replaced default tooltips with custom tooltips

fixed zoomslider sample and replaced data source

---

live-editing/configs/ComboConfigGenerator.ts

Combo binding sample did not have a correct ConfigGenerator and the StackBlitz buttons on combo.md were not working properly.

fix(combo): fix combo binding sample generator

---

src/app/grid/grid-conditional-row-selectors/grid-conditional-row-selectors-sample.component.html
src/app/grid/grid-conditional-row-selectors/grid-conditional-row-selectors-sample.component.scss
src/app/grid/grid-sample-selection-template-numbers/grid-sample-selection-template-numbers.component.scss
src/app/hierarchical-grid/hierarchical-grid-conditional-row-selectors/hierarchical-grid-conditional-row-selectors.component.html
src/app/hierarchical-grid/hierarchical-grid-conditional-row-selectors/hierarchical-grid-conditional-row-selectors.component.scss
src/app/hierarchical-grid/hierarchical-grid-selection-template-numbers/hierarchical-grid-selection-template-numbers.component.scss
src/app/tree-grid/tree-grid-conditional-row-selectors/tree-grid-conditional-row-selectors.component.html
src/app/tree-grid/tree-grid-conditional-row-selectors/tree-grid-conditional-row-selectors.component.scss
src/app/tree-grid/tree-grid-selection-template-numbers/tree-grid-selection-template-numbers.component.scss

By having moved padding on the default template https://github.com/IgniteUI/igniteui-angular/pull/5814 we no longer need to use `ng-deep` in the samples to apply `padding: 0`. We also have to make sure that every custom row/header template has padding applied to it. 
The conditional row selector samples did not have padding on the custom row selector template and this PR fixes this. This PR also removes the now redundant `ng-deep` declarations.

Update conditional row selectors samples and row numbering samples styles

---

src/app/grid/grid-editing-sample/grid-editing-sample.component.html

Fix for issue #1580.
Changing [valueKey] to [displayKey] for the combo editor.

Fixing #1580 - [Combo] Combo in grid editing sample is not properly bound

---

src/app/grid-crm/grid-crm/grid-crm.component.ts

Closes #1655 
This is a temporary fix for the export error. After the repos are divided, then also the sparklines will be exported in an excel file

Prevent sparkline column to be exported in grid CRM (vNext)

---

src/app/interactions/drag-drop/email-sample/email-sample.component.scss
src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.scss

Related issue #1758 
--
Resolves issue where fonts of the email and kanban samples could not be changed using the theming widget.

Removing default font-family from email and kanban samples

---

projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.scss

Fixes financial sample's slider labels' colors when a dark theme is applied - vNext

---

src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.html

Closes #2064
Change drop-down item to be bound to item's `ProductName` (unique key) instead of the object itself. Object reference is lost when new virtual chunk is loaded, leading to incorrect styling of selected items.

fix(drop-down): remote sample use proper unique value binding - master

---

src/app/data-entries/select/select-header-footer/select-header-footer.component.html
src/app/data-entries/select/select-header-footer/select-header-footer.component.scss
src/app/data-entries/select/select-header-footer/select-header-footer.component.ts
src/app/data-entries/select/select-sample-2/select-sample-2.component.html
src/app/data-entries/select/select-sample-2/select-sample-2.component.scss
src/app/data-entries/select/select-sample-2/select-sample-2.component.ts

Depends on https://github.com/IgniteUI/igniteui-angular/pull/7329
With the change to the content of the `igx-drop-down__item` (and, therefore, the select item), we need to make some changes to our sample in order to preserve their look:
The content of the select item is no longer `display: flex`, so we need to manually add that.
Since the item's content is part of the `igx-drop-down-item` template, we need to penetrate view encapsulation in both samples
To prevent style from "leaking", we need to scope by ':host' and use a display `outlet` for the overlay.
Finally, one of the samples was using `ViewEncapsulation.None` and was leaking styles - this is addressed.

fix(select): adjust select item content display to account for lib change

---

package-lock.json
package.json
src/app/data-display/icon/material-icons-extended/material-icons-extended.component.ts

Refactor the sample so that newly added categories are automatically added when a new version of the package is installed.

refactor(material-icons-extended): automate category declaration

---

src/app/grid/grid-sample-selection-template-numbers/grid-sample-selection-template-numbers.component.html

Closes #2358 
The `dataType` of the `City`, `PostalCode` and `CompanyName` columns was set to number which was causing the data piped into these columns to be treated as number by the decimalPipe.

fix(grid): Changing the dataType of the column components. #2358

---

src/app/grid/grid-sample-selection-template-numbers/grid-sample-selection-template-numbers.component.html

Closes #2358 
The `dataType` of the `City`, `PostalCode` and `CompanyName` columns was set to `number` which was causing the data piped into these columns to be treated as `number` by the decimalPipe.

fix(grid): Changing the dataType of the column component. #2358

---

src/app/tree-grid/tree-grid-row-reorder/tree-grid-row-reorder.component.ts

In `Tree Grid reorder`, do nothing if dragged row and targeted row are same (drag and drop in same row).
Same result when drag and drop in out of `Grid`.

do nothing if dragged row and targeted row are same

---

projects/app-lob/src/app/app.component.ts
src/app/app.component.ts

The Indigo themes don't apply fonts because Nunito Sans is obtained like this: `"Nunito Sans"` which leaves the quotations intact for the google-apis link

changing regex to match " as well for fonts

---

gulpfile.js

Closes #2686 
This PR should be tested on staging environment, since the wrongly replaced URL segments are applied on build

Change assets regex to handle relative paths

---

package-lock.json
package.json
src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts

Closes #2688
Use Hindi for custom obj sample, as Latin is unavailable in Angular framework for currencies and stuff in the sample.

Use BG localization strings from i18n package. Use Hindi for custom i18n

---

projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss

Fix SignalR sample icons - master

---

angular.json

With source map, performance is worse and also some erros occur after compile:

Disable ssource Map

---

src/app/data-display/icon/material-icons-extended/material-icons-extended.component.ts

Closes IgniteUI/igniteui-angular/issues/10583

fix(icons): material icons extended don't load

---

src/app/grid/grid-action-strip/grid-action-strip-sample.html
src/app/grid/grid-action-strip/grid-action-strip-sample.scss
src/app/grid/grid-action-strip/grid-action-strip-sample.ts
src/app/hierarchical-grid/hierarchical-grid-action-strip/hierarchical-grid-action-strip-sample.html
src/app/hierarchical-grid/hierarchical-grid-action-strip/hierarchical-grid-action-strip-sample.scss
src/app/hierarchical-grid/hierarchical-grid-action-strip/hierarchical-grid-action-strip-sample.ts
src/app/tree-grid/tree-grid-action-strip/tree-grid-action-strip-sample.html
src/app/tree-grid/tree-grid-action-strip/tree-grid-action-strip-sample.scss
src/app/tree-grid/tree-grid-action-strip/tree-grid-action-strip-sample.ts

Closes #3014 
1. Grid
- in html file - add **primaryKey**
- in ts file - changes in **startEdit** method
2. Hierarchical Grid
- the same as the Grid 
3. Tree Grid
- in html file - add a reference to the tree-grid, i.e., **#treeGrid**
- in ts file - same as the above two
1. Add **ng-container** with ***ngIf** check to hide action strip custom buttons when editing
2. Changes in **isDirty** method to show 'Undo All', 'Redo All' and 'Save' icons properly
1. Removed styling for missing **h4 tag**, added missing styling for classes used for **Photo** column in hGrid sample
2. Removed unused methods and properties, like **stateFormatter**, **typeFormatter**, etc.
3. Changed how the **dataType** property is set (some are set with square brackets and others without square brackets) and added …

Refactor row actions samples

---

projects/app-lob/src/app/grid-finjs/controllers.component.html
projects/app-lob/src/app/grid-finjs/controllers.component.ts
projects/app-lob/src/app/grid-finjs/main.component.html
projects/app-lob/src/app/grid-finjs/main.component.ts
projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
src/styles.scss

We are removing the switch because the finjs sample can now be styled with the theming widget.

removing the dark theme switch

---

src/app/data/hierarchical-data.ts
src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.html
src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.ts
src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.html
src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.ts
src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.html
src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.ts

fix(hierarchical grid): add richer data and a few new columns

---

src/app/data/singersData.ts

Related to this [issue](https://github.com/IgniteUI/igniteui-angular-samples/issues/3132).
Fix missing grid samples, tested on node version 16.19.0.
Tested both `default` and `Line of Business App` app version.

Chore(*): Fix missing grid samples

---

src/app/lists/combo/combo-template/combo-template.component.html

PS: Those could also be optimized with the short template syntax `*igxComboEmpty` to reduce the ng-template bulk if it's not needed:
```html
<span *igxComboEmpty class="empty-class">No available states</span>
```

fix(combo): remove duplicate igx-combo in template sample

---

src/app/grid/grid-cascading-combos/grid-cascading-combos.component.html
src/app/grid/grid-cascading-combos/grid-cascading-combos.component.ts

Refactor Grid Cascading Combos sample to handle vritualized grid scenario

---

src/app/data-display/mask/mask-sample-4/mask-sample-4.component.html
src/app/data-display/mask/mask-sample-4/mask-sample-4.component.ts

fix(mask): ensure single % appended on blur and removed on focus

---

src/app/grid/grid-row-editing-style/grid-row-editing-style.component.html

docs(grid): updated sample grid columns type

---

src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.html
src/app/layouts/carousel/carousel-no-navigation-sample/carousel-no-navigation-sample.component.html

fix(carousel): use indicators input property

---

projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts
src/app/tree-grid/tree-grid-filtering-sample/tree-grid-filtering-sample.component.ts

In the Filtering samples for Grid & Tree Grid, when you enter a filter value the Filter UI chip on the respective column is added, except when the filter input is cleared it remains with no value:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering#angular-grid-filtering-example
https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/filtering#angular-tree-grid-filtering-example
~Technically the same should be applied to the Boston Marathon and Filter template samples, since those do the same, except the UI is not active and thus isn't visible.~ Strike that, the Filter template samples actually have a check and clear, leaving just the landing grid sample, so I'll just go ahead and update it as well.

fix(grid,filtering): clear filter with empty input

---

package-lock.json
package.json
projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.html
projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
projects/app-lob/src/app/index/index.component.scss

fix(data-analysis): charts update functionality and extras update

---

src/app/interactions/overlay/overlay-styling/overlay-styling.component.html
src/app/interactions/overlay/overlay-styling/overlay-styling.component.ts

fix(overlay): fix combo binding in overlay styling demo

---

src/app/interactions/query-builder/query-builder-request-sample/query-builder-request-sample.component.ts
src/app/interactions/query-builder/query-builder-sql-sample/query-builder-sql-sample.component.ts

Fix for grid being empty after changing entity in samples located here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/query-builder-model

fix(query-builder): fix columns hidden when return fields is '*'

---

src/app/scheduling/daterangepicker/daterangepicker-start-end/daterangepicker-start-end.html
src/app/scheduling/daterangepicker/daterangepicker-start-end/daterangepicker-start-end.ts
src/app/scheduling/daterangepicker/daterangepicker-styling/daterangepicker-styling.html
src/app/scheduling/daterangepicker/daterangepicker-styling/daterangepicker-styling.ts
src/app/scheduling/daterangepicker/daterangepicker-validation/daterangepicker-validation.html
src/app/scheduling/daterangepicker/daterangepicker-validation/daterangepicker-validation.ts

feat(date-range-picker): add toggle and clear icons to both inputs
