- src/app/progressbar/progressbar.component.ts
- src/app/slider/slider.component.ts
- src/app/toast/toast.component.html
> change encapsulation into slider and progressbar component

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/navbar/navbar.component.css
- src/app/navbar/navbar.component.html
- src/app/navbar/navbar.component.spec.ts
- src/app/navbar/navbar.component.ts
- src/app/scroll/scroll.component.css
- src/app/scroll/scroll.component.html
- src/app/scroll/scroll.component.spec.ts
- src/app/scroll/scroll.component.ts
- src/app/tabbar/tabbar.component.css
- src/app/tabbar/tabbar.component.html
- src/app/tabbar/tabbar.component.spec.ts
- src/app/tabbar/tabbar.component.ts
> add navbar, scroll and tabbar samples

- src/app/grid/services/data.ts
> Updating CountryFlag paths

- src/app/list/list-sample-4/list-sample-4.component.html
- src/app/list/list-sample-4/list-sample-4.component.ts
- src/app/tabbar/tabbar.component.ts
Closes https://github.com/IgniteUI/igniteui-docfx/issues/17
> Tabbar images#17

- .angular-cli.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/buttons/buttons.component.ts
- src/app/grid/grid.component.html
- src/app/grid/grid.component.ts
- src/app/list/list-sample-4/list-sample-4.component.ts
- src/app/list/list.component.ts
- src/app/navdrawer/navdrawer.component.ts
- src/app/progressbar/progressbar.component.ts
- src/app/scroll/scroll.component.ts
- src/app/slider/slider.component.ts
- src/app/snackbar/snackbar.component.ts
- src/app/toast/toast.component.css
- src/app/toast/toast.component.ts
> Updating package.json with igniteui-angular

- package.json
> Fixed building of files for live editing

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/icon/icon-sample-1/icon-sample-1.component.css
- src/app/icon/icon-sample-1/icon-sample-1.component.html
- src/app/icon/icon-sample-1/icon-sample-1.component.ts
Related to IgniteUI/igniteui-docfx#100
Icon samples rework.
> Icon samples rework.

- .angular-cli.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/carousel/carousel-details/carousel-details.component.ts
- src/app/carousel/carousel-sample-2/carousel-sample-2.component.ts
- src/app/carousel/carousel-sample-3/carousel-sample-3.component.ts
- src/app/carousel/carousel-sample-4/carousel-sample-4.component.ts
- src/app/list/list-sample-4/list-sample-4.component.ts
- src/app/navdrawer/navdrawer.component.css
- src/app/navdrawer/navdrawer.component.html
- src/app/navdrawer/navdrawer.component.ts
- src/app/progressbar/progressbar.component.ts
- src/app/snackbar/snackbar.component.ts
- src/styles.css
Related #65 
https://github.com/IgniteUI/igniteui-angular/pull/541 
https://github.com/IgniteUI/igniteui-angular/issues/536
> Rename modules to 5.2.0

- src/app/badge/badge-sample-3/badge-sample-3.component.css
- src/app/badge/badge-sample-3/badge-sample-3.component.html
> Changed demo app to reflect the badge modifications

- live-editing/samples.conf.js
- src/app/app-routing.module.ts
- src/app/navbar/navbar.component.ts
Add live-editing config for all available samples.
> Update live-editing config

- src/app/list/list-sample-1/list-sample-1.component.html
- src/app/tabbar/tabbar.component.html
- src/app/tabbar/tabbar.component.ts
Updating igx-list samples to reflect the breaking changes introduced in 5.2. As a result the build is also fixed.
> Fixing igx-list samples

- web.config
> Added mime map for .json files.

- live-editing/samples.conf.js
> Fixes for badge sample in stackblitz

- src/app/app-routing.module.ts
> Added routing to toggle sample 3.

- src/app/buttonGroup/button-group-sample-1/button-group-sample-1.component.ts
- src/app/buttonGroup/button-group-sample-2/button-group-sample-2.component.ts
- src/app/buttonGroup/button-group-sample-3/button-group-sample-3.component.ts
This is related to #109 2. and 3.
> Changing ButtonGroup Samples.

- src/app/grid/grid.component.css
- src/app/grid/grid.component.html
- src/app/grid/grid.component.ts
> Update Grid Sample

- src/app/calendar/calendar-sample-1/calendar-sample-1.component.css
- src/app/calendar/calendar-sample-1/calendar-sample-1.component.html
- src/app/calendar/calendar-sample-5/calendar-sample-5.component.css
- src/app/carousel/carousel-sample-1/carousel-sample-1.component.css
> Fix calendar samples height

- src/app/carousel/carousel-sample-1/carousel-sample-1.component.css
- src/app/carousel/carousel-sample-2/carousel-sample-2.component.css
- src/app/carousel/carousel-sample-3/carousel-sample-3.component.css
- src/app/carousel/carousel-sample-4/carousel-sample-4.component.css
> Calendar samples

- src/app/grid/grid.component.html
- src/app/grid/grid.component.scss
> Make grid-sample responsive

- src/app/calendar/calendar-sample-1/calendar-sample-1.component.scss
- src/app/calendar/calendar-sample-2/calendar-sample-2.component.scss
- src/app/calendar/calendar-sample-4/calendar-sample-4.component.html
- src/app/calendar/calendar-sample-4/calendar-sample-4.component.scss
- src/app/calendar/calendar-sample-4/calendar-sample-4.component.ts
- src/app/calendar/calendar-sample-5/calendar-sample-5.component.scss
- src/app/date-parser.ts
- src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.html
- src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.ts
>  Calendar template parts parsing for browser not supporting Intl

- live-editing/SampleAssetsGenerator.ts
- live-editing/configs/MaskConfigGenerator.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/mask/mask-sample-1/mask-sample-1.component.html
- src/app/mask/mask-sample-1/mask-sample-1.component.scss
- src/app/mask/mask-sample-1/mask-sample-1.component.ts
- src/app/mask/mask-sample-2/mask-sample-2.component.html
- src/app/mask/mask-sample-2/mask-sample-2.component.ts
- src/app/mask/mask-sample-3/mask-sample-3.component.html
- src/app/mask/mask-sample-3/mask-sample-3.component.scss
- src/app/mask/mask-sample-3/mask-sample-3.component.ts
- src/app/mask/model/person.ts
> Added samples for mask directive

- src/app/grid/grid-sample-2/grid-sample-2.component.html
- src/app/grid/grid-sample-2/grid-sample-2.component.scss
Related to https://github.com/IgniteUI/igniteui-docfx/pull/236#pullrequestreview-109235048
> Adding some additional styles for igxGrid Performance sample.

- src/app/grid/grid-sample-2/grid-sample-2.component.html
- src/app/grid/grid-sample-2/grid-sample-2.component.scss
> Apply "Grid Performance Sample" feedback

- src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
- src/app/grid/grid-paging-sample/grid-paging-sample.component.html
> Make filtering sample respond to frame shrinking/expanding

- src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
- src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
- src/app/grid/grid.component.html
- src/app/grid/grid.component.scss
> fix styling issues on grid samples

- src/app/app-routing.module.ts
- src/app/category-chart/axis-options/category-chart-axis-options-sample.component.html
- src/app/category-chart/axis-options/category-chart-axis-options-sample.component.scss
- src/app/category-chart/axis-options/category-chart-axis-options-sample.component.ts
- src/app/category-chart/category-chart-samples.module.ts
- src/app/category-chart/config-options/category-chart-config-options-sample.component.html
- src/app/category-chart/config-options/category-chart-config-options-sample.component.scss
- src/app/category-chart/config-options/category-chart-config-options-sample.component.ts
> added new samples for CategoryChart

- src/app/grid/grid-sample-selection/grid-selection.component.ts
Change the default value of the rowSelectable attribute in the selection sample from **false** to **true**
> Grid Selection Sample - Default Value

- src/app/app-routing.module.ts
- src/app/financial-chart/axis-types/financial-chart-axis-types.component.html
- src/app/financial-chart/axis-types/financial-chart-axis-types.component.ts
- src/app/financial-chart/financial-chart-samples.module.ts
- src/app/financial-chart/trendlines/financial-chart-trendlines.component.html
- src/app/financial-chart/trendlines/financial-chart-trendlines.component.ts
this PR is required for Angular docs
> added trendlines sample and fix other FC samples

- src/app/grid/grid-crm/grid-crm.component.html
- src/app/grid/grid-crm/grid-crm.component.scss
1. Fix the stylings for the drop-down menu in the header
2. Fix Avatar cut off
3. Change class name form "switch-sample" to "crm-sample"
> Fix crm-grid styling

- src/app/grid/grid.component.html
> remove date column from awesome grid sample

- src/app/category-chart/axis-options/category-chart-axis-options-sample.component.html
- src/app/category-chart/axis-options/category-chart-axis-options-sample.component.ts
- src/app/category-chart/config-options/category-chart-config-options-sample.component.html
- src/app/category-chart/config-options/category-chart-config-options-sample.component.ts
- src/app/category-chart/custom-tooltips/category-chart-custom-tooltips-sample.component.html
- src/app/category-chart/overview/category-chart-overview-sample.component.html
- src/app/category-chart/overview/category-chart-overview-sample.component.ts
- added Area chart type
- changed data source in CC samples to avoid hiding of series when using
chart types with area fill
- adjusted axis settings to work with new data source
- minor styling fixes
> changed data source in CC samples

- src/app/financial-chart/custom-tooltips/financial-chart-custom-tooltips.component.html
- src/app/financial-chart/custom-tooltips/financial-chart-custom-tooltips.component.ts
- src/app/financial-chart/overview/financial-chart-overview-sample.component.html
- src/app/financial-chart/overview/financial-chart-overview-sample.component.ts
- src/app/financial-chart/panes/financial-chart-panes.component.ts
- src/app/financial-chart/services/generate-hourly-prices.service.ts
- src/app/financial-chart/services/generate-ohlc-prices.service.ts
- src/app/financial-chart/services/stock-data.service.ts
- src/app/financial-chart/titles/financial-chart-titles.component.ts
this PR fixes issue #247 and issue with tooltips that were not reported
> fixed issues with tooltips and data source

- live-editing/configs/CalendarConfigGenerator.ts
- live-editing/configs/CardConfigGenerator.ts
- live-editing/configs/CarouselConfigGenerator.ts
- live-editing/configs/DatePickerConfigGenerator.ts
- live-editing/configs/DialogConfigGenerator.ts
- live-editing/configs/ForConfigGenerator.ts
- live-editing/configs/MaskConfigGenerator.ts
- live-editing/configs/ToggleConfigGenerator.ts
> Add missing module imports and remove some shorten paths

- src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.html
- src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
> Adding a height to the igxGrid to fix an issue in the exporters samples.

- live-editing/SampleAssetsGenerator.ts
> docs(grid): Adding support for forRoot with 1 param

- src/app/igxFor/igxFor.component.html
> Fix vertical scrollbar in igxForOf demo not displaying properly.

- package.json
- src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
- src/app/grid/grid-paging-sample/grid-paging-sample.component.html
- src/app/grid/grid-sample-3/grid-sample-3.component.html
- src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html
> Enhance some of the grid samples

- live-editing/DependencyResolver.ts
- live-editing/configs/ExportCsvConfigGenerator.ts
- live-editing/configs/ExportExcelConfigGenerator.ts
- live-editing/configs/GridConfigGenerator.ts
- package.json
Fixing CSV/Excel samples until #234 is resolved.
> Added immediate package to CSV/Excel live editing samples

- package.json
- src/app/category-chart/high-frequency/category-chart-high-frequency-sample.component.html
- src/app/category-chart/high-frequency/category-chart-high-frequency-sample.component.scss
- src/app/category-chart/high-frequency/category-chart-high-frequency-sample.component.ts
- src/app/category-chart/high-volume/category-chart-high-volume-sample.component.html
- src/app/category-chart/high-volume/category-chart-high-volume-sample.component.ts
- fixed formatting of numbers
- fixed size of sliders
- added link to samples repo
> fixed category chart samples

- .github/CONTRIBUTING.md
- README.md
> Adding readme.md and contributing.md files

- src/app/category-chart/custom-tooltips/category-chart-custom-tooltips-sample.component.html
- src/app/category-chart/high-frequency/category-chart-high-frequency-sample.component.ts
- src/app/category-chart/high-volume/category-chart-high-volume-sample.component.ts
- CC high frequency sample does not use any formatting/abbreviating of labels
- CC high volume sample uses formatting/abbreviating of labels
> Fixed CC tooltips and span formatting above slider

- src/app/grid/grid-sample-3/grid-sample-3.component.html
> Setting width 15% to the last column in grid-summary sample

- src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
> fix(grid-filtering): set percentage width to the last column

- src/app/grid/grid.component.ts
> fix(grid-sample): return where is no data for summaries

- .angular-cli.json
- package-lock.json
- package.json
- src/app/grid/grid-crm/grid-crm.component.html
- src/app/grid/grid-crm/grid-crm.component.scss
- src/app/grid/grid-sample-pinning/grid-pinning.component.html
- src/app/grid/grid-sample-pinning/grid-pinning.component.scss
- src/app/grid/grid-sample-pinning/grid-pinning.component.ts
- src/styles.scss
> Changed the column pinning icon to fa-thumbtack in the grid-column-pinning sample

- .angular-cli.json
- package-lock.json
- package.json
- src/app/grid/grid-crm/grid-crm.component.html
- src/app/grid/grid-crm/grid-crm.component.scss
- src/app/grid/grid-sample-pinning/grid-pinning.component.html
- src/app/grid/grid-sample-pinning/grid-pinning.component.scss
- src/app/grid/grid-sample-pinning/grid-pinning.component.ts
- src/styles.scss
> Changed the column pinning icon to fa-thumbtack in the grid-column-pinning sample - 5.3.x

- src/app/grid/grid.component.ts
> fix(marahon-grid): check whether data exist more safety

- src/app/grid/grid-sample-2/grid-sample-2.component.html
- src/app/grid/grid-sample-4/grid-sample-4.component.html
- src/app/grid/grid-sample-selection/grid-selection.component.html
> Remove 'cellAlignStyle' from header templates

- src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
- src/app/grid/grid-paging-sample/grid-paging-sample.component.ts
- src/app/grid/grid.component.scss
> align items in the pager template

- src/app/card/card.component.html
- src/app/card/card.component.scss
- src/styles.scss
> set body overflow to hidden, enhance the card sample

- src/app/tabbar/tabbar.component.scss
> styles(tabbar-list) Fix misaligned list items in IE

- src/app/grid/grid.component.ts
- src/polyfills.ts
> Remove Intl polyfills, remove forEach usage in grid sample

- src/app/grid/grid-crm/grid-crm.component.scss
> Fix flickering search input

- src/app/grid/grid-crm/grid-crm.component.scss
> fix(crm-grid): Fix filtering dialog input

- src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
> remove unnessesary styles

- package-lock.json
- package.json
- src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts
- src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.ts
- src/app/grid/grid.component.ts
- src/app/grid/services/remoteFilteringService.ts
- src/app/toggle/toggle-sample-3/toggle-sample-3.component.html
Related to IgniteUI/igniteui-angular#1355
Closes #420
> docs(grid): Filtering samples updated with the latest changes #1355

- src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html
> fix(groupbysample): Removing primaryKey

- src/app/grid/grid.component.scss
- src/app/grid/grid.component.ts
> Fix for misaligned cup image and filtered empty summary

- src/app/grid/grid-crm/grid-crm.component.html
adding movable="true" to all column in the Grid CRM sample
> Making all columns of the Grid CRM sample movable

- live-editing/configs/GridConfigGenerator.ts
> Add missing Badge module

- src/app/dropdown/dropdown-sample-1/dropdown-sample-1.component.html
- src/app/dropdown/dropdown-sample-2/dropdown-sample-2.component.html
- src/app/dropdown/dropdown-sample-3/dropdown-sample-3.component.html
Adding Keyboard navigation for drop-down samples.
Note: Expected to work after an overlay related fix.
> I ganchev add dropdown new proj structure

- live-editing/configs/core/AppModuleConfig.ts
- live-editing/generators/SampleAssetsGenerator.ts
- live-editing/templates/app.module.ts.template
> Added live editing entry components support

- src/app/grid/grid-sorting-sample/grid-contextmenu/grid-contextmenu.component.ts
> fix(sample): Fixing sort method signature.

- src/app/grid/grid-crm/grid-crm.component.scss
> style(crm-grid): fix text color for selected row

- src/app/grid/grid-crm/grid-crm.component.scss
> style(crm-grid): Fix the problem with ng-deep for CRM sample

- src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.html
- src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.scss
- src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.ts
- src/app/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.scss
- src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.scss
ScrollStrategy sample now has scrollbar to show the functionality
AutoPositionStrategy square added to the demo for positioning strategies
> Add scroll to Scrolling sample, add AutoPosition to demo

- package-lock.json
- src/app/grid/grid-paging-sample/grid-paging-sample.component.html
- src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
- src/app/grid/grid.component.html
- src/app/grid/grid.component.scss
> provide parent element for linear-bar in templated cells

- src/app/grid/grid-crm/grid-crm.component.html
- src/app/grid/grid-crm/grid-crm.component.ts
> fix(igxGrid): Implement positioning strategy for igxToggle #482

- src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
> Updated cellEditing sample

- src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
> docs(grid): Fixed styling issue in the column moving sample #492

- src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.scss
> fixing margin so the igxGrid can occupy more space

- src/app/combo/combo-features/combo-features.component.html
Closes #496.
Bind to Combo onOpening event and get full data set
> Combo - Remote Data Sample - Get data on opening

- src/app/app.module.ts
- src/app/overlay/overlay-dynamic-card/overlay-dynamic-card.component.ts
- src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.html
- src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.ts
Change scroll strategy in scroll-sample-2 from Global to Connected to highligh how AbsoluteScrollStrategy works
> Overlay - Adjust positioning strategy in scroll demo

- web.config
> Added root redirect

- live-editing/configs/OverlayConfigGenerator.ts
Add MyDynamicCardComponent to OverlayConfigGenerator
> Overlay - Scroll Strategy Sample - Fix Stackblitz Demo

- src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.html
- src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.ts
- src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.html
- src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.ts
- src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.html
- src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.ts
updated styling of gauges based on Andie's request
> updated styling of gauges

- src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.html
- src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.scss
- src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.ts
- src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.html
- src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.scss
- src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.ts
- src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.html
- src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.ts
added 3-4 views to each gauge samples and enabled animation transition between each view
> Updated gauge samples

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/grid/grid-paste/data.ts
- src/app/grid/grid-paste/grid-paste-sample.component.html
- src/app/grid/grid-paste/grid-paste-sample.component.scss
- src/app/grid/grid-paste/grid-paste-sample.component.ts
- src/app/grid/grid-paste/paste-handler.directive.ts
> Adding basic paste from excel sample - 6.1.x

- src/app/grid/grid-paste/paste-handler.directive.ts
> Adding handling for Cmd+V for Mac

- src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.html
- src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.scss
- src/app/grid/grid-sample-4/grid-sample-4.component.html
- src/app/grid/grid-sample-4/grid-sample-4.component.scss
1. Cut off grids in the [Grid Virtualization and Performance demo](https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_virtualization.html)
> fix(grid): Fixed cut-off samples

- src/app/combo/combo-features/combo-features.component.html
- src/app/combo/combo-features/combo-features.component.ts
> Add combo with remote data 

- live-editing/configs/ComboConfigGenerator.ts
- src/app/combo/combo-features/combo-features.component.html
- src/app/combo/combo-features/combo-features.component.ts
> Combo - Remote Data - Add loading indicator

- src/app/grid/grid-crm/grid-crm.component.html
- src/app/grid/grid-crm/grid-crm.component.ts
> CRM- sample summaries misalignment fix

- src/app/grid/grid-paste/paste-handler.directive.ts
> fix(*): #579 Pasting Excel data in the grid scrolls to the top of the page

- src/app/index/index.component.html
- src/app/index/index.component.scss
- src/app/index/index.component.ts
> Fix grid displaying issue when using navDrawer

- src/app/grid/grid-sample-3/grid-sample-3.component.html
- src/app/grid/grid-sample-3/grid-sample-3.component.scss
> Render summary icons with longer header when resizing and on Ipad resolution.

- src/app/grid/grid-moving-sample/grid-moving-sample.component.html
- src/app/grid/grid-moving-sample/grid-moving-sample.component.scss
> fix(column-moving): Fixed styling issue #564

- src/app/grid/grid-paste/data.ts
> docs(*): Removing one record from the exported excel

- live-editing/configs/DropDownConfigGenerator.ts
> IgxDropDown - StackBlitz - Buttons in sample now use IgxButton directive correctly

- src/polyfills.ts
> add core-js/es7/object pollyfill for IE

- live-editing/configs/TextHighlightConfigGenerator.ts
- live-editing/generators/SampleAssetsGenerator.ts
- src/app/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.html
- src/app/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.scss
- src/app/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.ts
- src/app/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.html
- src/app/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.scss
- src/app/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.ts
> Improve the samples for docfx

- src/app/app-routing.module.ts
- src/app/category-chart/category-chart-samples.module.ts
- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.html
- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.scss
- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.ts
- src/app/category-chart/trendline/category-chart-with-trendline.component.html
- src/app/category-chart/trendline/category-chart-with-trendline.component.scss
- src/app/category-chart/trendline/category-chart-with-trendline.component.ts
- added new sample for CC control:
- updated data and styling in CC trendline sample:
> PPC Chart Samples

- src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.html
- src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.scss
- src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.ts
> Added Options for changing AxisMode in FC sample

- src/index.html
> Adding igx-typography class

- live-editing/configs/TabsConfigGenerator.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/tabs/tabs-sample-4/app.routing.module.ts
- src/app/tabs/tabs-sample-4/components/tabs-sample-4.component.html
- src/app/tabs/tabs-sample-4/components/tabs-sample-4.component.scss
- src/app/tabs/tabs-sample-4/components/tabs-sample-4.component.ts
- src/app/tabs/tabs-sample-4/tabs-sample-4.module.ts
- src/app/tabs/tabs-sample-4/tabs.routing1.module.ts
- src/app/tabs/tabs-sample-5/app.routing.module.ts
- src/app/tabs/tabs-sample-5/components/tabs-sample-5.component.html
- src/app/tabs/tabs-sample-5/components/tabs-sample-5.component.ts
- src/app/tabs/tabs-sample-5/tabs-sample-5.module.ts
- src/app/tabs/tabs-sample-5/tabs.routing2.module.ts
- src/app/tabs/views/view1/view1.component.html
- src/app/tabs/views/view1/view1.component.ts
- src/app/tabs/views/view2/view2.component.html
- src/app/tabs/views/view2/view2.component.ts
- src/app/tabs/views/view3/view3.component.html
- src/app/tabs/views/view3/view3.component.ts
- src/app/tabs/views/views.module.ts
Related to IgniteUI/igniteui-angular#1957
> docs(tabs): Added tabs with routing sample in samples solution #1957

- src/app/chip/chip.component.ts
> Update igxChips sample to detect changes when dragging chips around.

- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.html
- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.scss
- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.ts
- src/app/financial-chart/financial-chart-samples.module.ts
- src/app/financial-chart/multiple-feeds/financial-chart-multiple-feeds.component.html
- src/app/financial-chart/multiple-feeds/financial-chart-multiple-feeds.component.scss
- src/app/financial-chart/multiple-feeds/financial-chart-multiple-feeds.component.ts
- src/app/financial-chart/services/financial-data.service.ts
- src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.html
- src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.scss
- src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.ts
- completed all requests from Jason except "click and drag to zoom chart" because we don't expose property to change default drag behavior in Angular.
- added legend to 3 chart samples
- added titles to 3 chart samples
- added workaround for issue with duplicated legend items in FC
- adjusted data source to mitigate issue with clipped tooltips
- corrected stock data for missing company names and invalid values
- improved performance in FC multiple feeds sample by removing code for rounding stock data
> Updated chart samples per Jason's request

- src/app/app-routing.module.ts
- src/app/grid/grid-remote-paging-sample/data-service/data-service.ts
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.ts
- src/app/grid/services/remotePagingService.ts
> Updating the remote paging sample.

- src/app/grid/grid-editing-sample/data.ts
- src/app/grid/grid-editing-sample/grid-editing-sample.component.html
- src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
- src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
- src/app/grid/grid-editing-sample/product.ts
Closes #640 
Add new column to Grid Editing Sample (`Locations`) that lists the stores at which the products are available. Edit mode template uses and `igx-combo` component bound to the cells value
> Enhancement - Grid - Add Combo Edit Template to Grid Editing Sample

- src/app/layout/layout.component.scss
- src/app/layout/layout.component.ts
Closes #654.
Related to https://github.com/IgniteUI/igniteui-docfx/issues/443.
> Fixed layout manager sample to be scrollable

- src/app/tooltip/tooltip-rich/tooltip-rich.component.html
- src/app/tooltip/tooltip-rich/tooltip-rich.component.scss
Fix rich tooltip sample image paths
#666
> Fix rich tooltip sample image paths

- src/app/toggle/toggle-sample-1/toggle-sample-1.component.html
- src/app/toggle/toggle-sample-1/toggle-sample-1.component.ts
- src/app/toggle/toggle.component.html
> Cleanup toggle samples.

- live-editing/configs/GridConfigGenerator.ts
Closes #675 
The sample threw an error in StackBlitz because of the IgxComboModule absence.
> Importing the IgxComboModule for IgxGridEditingSample.

- src/app/app-routing.module.ts
- src/app/category-chart/annotations/category-chart-annotations.component.html
- src/app/category-chart/annotations/category-chart-annotations.component.scss
- src/app/category-chart/annotations/category-chart-annotations.component.ts
- src/app/category-chart/category-chart-samples.module.ts
- src/app/financial-chart/annotations/financial-chart-annotations.component.html
- src/app/financial-chart/annotations/financial-chart-annotations.component.scss
- src/app/financial-chart/annotations/financial-chart-annotations.component.ts
- src/app/financial-chart/financial-chart-samples.module.ts
- src/app/utilities/keys-pipe.ts
- src/app/utilities/utilities.module.ts
re-added mikeH's samples for chart's annotations due to build errors in his PR
> re-added mikeH's samples for chart's annotations

- live-editing/configs/DensityConfigGenerator.ts
- live-editing/generators/SampleAssetsGenerator.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/display-density/display-density.component.html
- src/app/display-density/display-density.component.scss
- src/app/display-density/display-density.component.ts
Related to IgniteUI/igniteui-angular#2692
> docs(*): Sample for display density #2692

- live-editing/configs/GridConfigGenerator.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/grid/grid-custom-filtering/grid-custom-filtering.component.html
- src/app/grid/grid-custom-filtering/grid-custom-filtering.component.scss
- src/app/grid/grid-custom-filtering/grid-custom-filtering.component.ts
> docs(grid): Added filtering sample for custom operators #706

- package-lock.json
this PR should fix build issue http://tfs.infragistics.local:8080/tfs/Engineering/NetAdvantage/_build/index?buildId=700678&_a=summary&tab=details
> re-generated package-lock file

- src/app/excel-library/operations-on/workbooks.component.html
- src/app/excel-library/operations-on/workbooks.component.ts
- src/app/excel-library/operations-on/workbooks.module.ts
- src/app/excel-library/working-with/charts.component.html
- src/app/excel-library/working-with/charts.module.ts
- src/app/excel-library/working-with/sparklines.component.html
- src/app/excel-library/working-with/sparklines.component.ts
> Updated Workbook sample and Styled Excel charts

- src/app/excel-library/operations-on/workbooks.component.html
- src/app/excel-library/operations-on/workbooks.component.scss
- src/app/excel-library/operations-on/workbooks.component.ts
- src/app/excel-library/operations-on/workbooks.module.ts
- src/app/excel-library/working-with/grids.component.html
- src/app/excel-library/working-with/grids.component.ts
- src/app/excel-library/working-with/grids.module.ts
- tsconfig.json
> added excel sample for workbooks and grid

- src/app/category-chart/annotations/category-chart-annotations.component.html
- src/app/category-chart/annotations/category-chart-annotations.component.scss
- src/app/category-chart/annotations/category-chart-annotations.component.ts
- src/app/category-chart/config-options/category-chart-config-options-sample.component.ts
- src/app/category-chart/highlighting/category-chart-highlighting.component.ts
- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.html
- src/app/category-chart/overlap-columns/category-chart-overlap-columns.component.ts
- src/app/category-chart/overview/category-chart-overview-sample.component.ts
- src/app/category-chart/tooltip-template/category-chart-tooltip-template.component.ts
- src/app/category-chart/tooltip-types/category-chart-tooltip-types.component.ts
- src/app/category-chart/trendline/category-chart-trendlines.component.ts
- src/app/excel-library/working-with/charts.component.ts
- src/app/excel-library/working-with/sparklines.component.ts
- src/app/financial-chart/annotations/financial-chart-annotations.component.ts
- src/app/financial-chart/overview/financial-chart-overview-sample.component.ts
- src/app/financial-chart/time-based-data/financial-chart-time-based-data.component.ts
- src/app/financial-chart/tooltip-types/financial-chart-tooltip-types.component.ts
added ChangeDetectionStrategy
correct styling of some samples
> added ChangeDetectionStrategy

- package-lock.json
- package.json
Updating igniteui-angular version to 7.0.3-beta.0
> Update to beta.0

- src/app/grid/grid-custom-filtering/grid-custom-filtering.component.ts
Closes IgniteUI/igniteui-angular/issues/3433
> Fix the custom filtering conditions sample

- src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.html
#IgniteUI/igniteui-docfx/issues/904
> Fixing a sample height

- src/app/grid/grid-finjs-demo/grid-finjs-demo.component.html
- src/app/grid/grid-finjs-demo/grid-finjs-demo.component.scss
- src/app/grid/grid-finjs-demo/grid-finjs-demo.component.ts
- src/app/grid/services/localData.service.ts
- src/app/tree-grid/tree-grid-finjs/tree-grid-finjs-sample.component.html
- src/app/tree-grid/tree-grid-finjs/tree-grid-finjs-sample.component.scss
- src/app/tree-grid/tree-grid-finjs/tree-grid-finjs-sample.component.ts
> update FinJs demos

- src/app/tree-grid/tree-grid-finjs/tree-grid-finjs-sample.component.html
Closes #834 (the last issue in the list)
> make the treegrid sample take the whole height

- src/app/localization-samples/localization-sample-1/localization-sample-1.component.html
- src/app/localization-samples/localization-sample-2/localization-sample-2.component.html
- src/app/localization-samples/localization-sample-3/localization-sample-3.component.html
> Fix localization samples width for IE 11.

- src/app/grid/grid-finjs-demo/grid-finjs-demo.component.scss
- src/app/tree-grid/tree-grid-finjs/tree-grid-finjs-sample.component.scss
> fix(finjs-grid): fix finjs group area height in IE 11

- src/app/grid/grid-crm/grid-crm.component.html
> #848 Fixed an issue with Propeller grid in IE11.

- src/app/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
> Fixing the igxRippleTarget

- src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
- src/app/theming/default-theme-sample/default-theme-sample.component.scss
> Adding simple colors to add product button in grid_eding and default-theme samples

- src/app/app.module.ts
Clearing out the app.module.ts from excessive imports.
#776
> clearing out the app.module

- live-editing/generators/SampleAssetsGenerator.ts
> Adding the services routing to the sample routes

- package-lock.json
- package.json
> Sass.js version update

- src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.html
- src/app/data-entries/input-group/reactive-forms/reactive-forms.component.html
- src/app/data-entries/input-group/reactive-forms/reactive-forms.component.scss
- src/app/grid/grid-editing-sample/grid-editing-sample.component.html
- src/app/scheduling/datepicker/datepicker-sample-1/datepicker-sample-1.component.html
- src/app/scheduling/datepicker/datepicker-sample-2/datepicker-sample-2.component.html
- src/app/scheduling/datepicker/datepicker-sample-3/datepicker-sample-3.component.html
- src/app/scheduling/datepicker/datepicker-sample-4/datepicker-sample-4.component.html
- src/app/scheduling/datepicker/datepicker-sample-5/datepicker-sample-5.component.html
- src/app/theming/dark-theme-sample/dark-theme-sample.component.html
- src/app/theming/default-theme-sample/default-theme-sample.component.html
- src/app/theming/theme-chooser/theme-chooser-sample.component.html
Related to IgniteUI/igniteui-angular#2386
> fix(date-picker): Updated date picker selector in samples #2386

- .vscode/launch.json
- README.md
- live-editing/LiveEditingManager.ts
- live-editing/README.md
- live-editing/configs/LocalizationConfigGenerator.ts
- live-editing/generators/ConfigGenerators.ts
- live-editing/generators/Generator.ts
- live-editing/generators/Routes.ts
- live-editing/generators/SampleAssetsGenerator.ts
- live-editing/services/DependencyResolver.ts
- live-editing/services/TsImportsService.ts
- package-lock.json
- package.json
> Live editing refactoring

- src/app/data-display/badge/badge-sample-3/badge-sample-3.component.html
- src/app/data-display/badge/badge-sample-3/badge-sample-3.component.scss
> Fixing badges samples

- src/app/layouts/tabbar/tabbar.component.html
> Changing ripple target for tabbar sample

- src/app/charts/data-chart/data-chart-overview/data-chart-overview.component.html
- src/app/charts/data-chart/data-chart-overview/data-chart-overview.component.scss
- src/app/charts/data-chart/data-chart-overview/data-chart-overview.component.ts
> Mtp igniteui angular samples overview

- src/app/charts/data-chart/data-chart-series-markers/data-chart-series-markers.component.html
- src/app/charts/data-chart/data-chart-series-markers/data-chart-series-markers.component.scss
- src/app/charts/data-chart/data-chart-series-markers/data-chart-series-markers.component.ts
> Mtp igniteui angular samples seriesmarkers

- src/app/charts/data-chart/data-chart-samples-module.ts
- src/app/charts/data-chart/data-chart-type-scatter-area-series/data-chart-type-scatter-area-series.component.html
- src/app/charts/data-chart/data-chart-type-scatter-area-series/data-chart-type-scatter-area-series.component.scss
- src/app/charts/data-chart/data-chart-type-scatter-area-series/data-chart-type-scatter-area-series.component.ts
> Mtp igniteui angular samples scatter area

- package-lock.json
- src/app/charts/data-chart/data-chart-type-category-series/data-chart-type-category-series.component.html
- src/app/charts/data-chart/data-chart-type-category-series/data-chart-type-category-series.component.scss
- src/app/charts/data-chart/data-chart-type-category-series/data-chart-type-category-series.component.ts
Category-Chart Sampe for DataChart
> mdd-260575

- live-editing/LiveEditingManager.ts
- live-editing/configs/DataChartConfigGenerator.ts
- live-editing/configs/DoughnutChartConfigGenerator.ts
- live-editing/generators/MetaDataGenerator.ts
- live-editing/generators/SampleAssetsGenerator.ts
- live-editing/generators/SharedAssetsGenerator.ts
- fixed config generator for DataChart and DoughnutChart
- added logs to live-editing components
> xsharp - fixed config generator for DataChart

- package-lock.json
- package.json
> revert package version for now

- .vscode/settings.json
- package.json
> Increased the RAM limit to 8 GB

- README.md
- package.json
> Introduced new command npm run start:live-editing

- live-editing/configs/GridConfigGenerator.ts
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.scss
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.ts
> Adding remote pagin sample with custom template

- src/app/index/index.component.ts
> Routing exception fix

- live-editing/configs/DatePickerConfigGenerator.ts
Related to: [IgniteUI/igniteui-angular#3034](https://github.com/IgniteUI/igniteui-angular/issues/3034)
And PR - https://github.com/IgniteUI/igniteui-angular-samples/pull/989
> Add config dor datepicker-dropdown

- src/app/grid-crm/grid-crm.module.ts
> Adding IgxCsvExporterService provider #1002

- src/app/theming/theme-chooser/theme-chooser-sample.component.ts
> Removing redundant outlet setting

- src/app/hierarchical-grid/hierarchical-grid-lod/hierarchical-grid-lod.component.ts
- src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.ts
> Add error handling for remote load on demand and paging samples for Hierarchical Grid.

- src/app/interactions/tooltip/tooltip-rich/tooltip-rich.component.scss
> Fix rich tooltip image sizing

- src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-paging.component.html
> Change page size for Hierarhical GHrid Paging sample to mach currently the valid values.

- src/app/hierarchical-grid/data.json
- src/app/hierarchical-grid/data.ts
- src/app/hierarchical-grid/hierarchical-grid-editing/data.ts
- src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-1/data.ts
- src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-2/data.ts
- src/app/hierarchical-grid/hierarchical-grid-filtering/data.ts
- src/app/hierarchical-grid/hierarchical-grid-row-editing/data.ts
> Changing the Date format in the data files

- live-editing/configs/ExportExcelConfigGenerator.ts
- src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
> Making export button an igxButton in Grid Export Excel sample

- live-editing/configs/ButtonGroupConfigGenerator.ts
- src/app/data-entries/buttonGroup/button-group-sample-1/button-group-sample-1.component.html
- src/app/data-entries/buttonGroup/button-group-sample-1/button-group-sample-1.component.scss
- src/app/data-entries/buttonGroup/button-group-sample-1/button-group-sample-1.component.ts
- src/app/data-entries/buttonGroup/button-group-sample-2/button-group-sample-2.component.html
- src/app/data-entries/buttonGroup/button-group-sample-2/button-group-sample-2.component.ts
- src/app/data-entries/buttonGroup/button-group-sample-3/button-group-sample-3.component.html
- src/app/data-entries/buttonGroup/button-group-sample-3/button-group-sample-3.component.ts
- src/app/data-entries/buttonGroup/button-group-sample-4/button-group-sample.component.html
- src/app/data-entries/buttonGroup/button-group-sample-4/button-group-sample.component.scss
- src/app/data-entries/buttonGroup/button-group-sample-4/button-group-sample.component.ts
- src/app/data-entries/data-entries-routes-data.ts
- src/app/data-entries/data-entries-routing.module.ts
- src/app/data-entries/data-entries.module.ts
Related to IgniteUI/igniteui-docfx#1006
Buttons listed in html, not in typescript for some samples
> docs(button-group): Reworked samples

- src/app/grid/grid-moving-sample/grid-moving-sample.component.html
> Fix Column Moving sample pinning in Chorme

- src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-custom-hiding.component.html
- src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-hiding.component.html
> Changing column's dataType to 'number' in the two igxHierarchicalGrid Hiding samples

- package-lock.json
- package.json
In order to test the PR just execute
- `npm run start`
- `npm run start:live-editing` (for aot and live-editing generation)
> Updating to verion 7.2.4

- src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-pinning.component.html
- src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.html
> Fixing the HGrid Editing and Pinning samples

- src/app/index/docs-layout.component.ts
Closes #1098 
This PR should be tested simultaneously  with this [PR](https://github.com/IgniteUI/igniteui-docfx-template/pull/93)
> Changing theme apllication and removal approach, because of IE 11 and Edge

- src/app/grid/grid-batch-editing/grid-batch-editing-sample.component.html
- src/app/grid/grid-editing-sample/grid-editing-sample.component.html
> Change cell's EditValue invocation in Grid Editing samples

- package-lock.json
- package.json
Run `npm run start` and `npm run start:live-editing`
> Updating to version 7.2.7

- src/app/grid/grid-multi-cell-selection/grid-multi-cell-selection.component.html
- src/app/grid/grid-multi-cell-selection/grid-multi-cell-selection.component.scss
- src/app/tree-grid/tree-grid-multi-cell-selection/tree-grid-multi-cell-selection.component.html
- src/app/tree-grid/tree-grid-multi-cell-selection/tree-grid-multi-cell-selection.component.scss
> Modify selection samples for grid and treegrid so columns are not cut

- package-lock.json
- package.json
Execute:
- npm run build
- npm run start:live-editing
> rc1 update

- src/app/grid-finjs/grid-finjs-demo.component.html
- src/app/grid-finjs/grid-finjs-demo.component.scss
- src/app/grid-finjs/grid-finjs-demo.component.ts
- src/app/index/index.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Set display density and use ExcelStyleFiltering on the finjs demos

- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/tree-grid/tree-grid-remote-paging-sample/remotePagingService.ts
- src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.html
- src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.scss
- src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid.module.ts
> Add tree grid remote paging sample

- src/app/grid/grid-row-drag-base/grid-row-drag-base.component.html
- src/app/grid/grid-row-drag-base/grid-row-drag-base.component.ts
- src/app/grid/grid-row-drag-to-grid/grid-row-drag-to-grid.component.html
- src/app/grid/grid-row-drag-to-grid/grid-row-drag-to-grid.component.ts
- src/app/grid/grid-row-drag/grid-row-drag.component.html
- src/app/grid/grid-row-drag/grid-row-drag.component.ts
- src/app/hierarchical-grid/hierarchical-grid-row-drag-base/hierarchical-row-drag-base.component.html
- src/app/hierarchical-grid/hierarchical-grid-row-drag-base/hierarchical-row-drag-base.component.ts
- src/app/hierarchical-grid/hierarchical-grid-row-drag/hierarchical-grid-row-drag.component.html
- src/app/hierarchical-grid/hierarchical-grid-row-drag/hierarchical-grid-row-drag.component.ts
- src/app/tree-grid/tree-grid-row-drag-base/tree-grid-row-drag-base.component.html
- src/app/tree-grid/tree-grid-row-drag-base/tree-grid-row-drag-base.component.ts
- src/app/tree-grid/tree-grid-row-drag/tree-grid-row-drag.component.html
- src/app/tree-grid/tree-grid-row-drag/tree-grid-row-drag.component.ts
> Adding animations to the row drag samples

- live-editing/configs/SliderConfigGenerator.ts
- package-lock.json
- package.json
- src/app/interactions/interactions-routes-data.ts
- src/app/interactions/interactions-routing.module.ts
- src/app/interactions/interactions.module.ts
- src/app/interactions/slider/slider-sample-3/slider-sample-3.component.scss
- src/app/interactions/slider/slider-sample-4/slider-sample-4.component.scss
- src/app/interactions/slider/slider-sample-5/slider-sample-5.component.scss
- src/app/interactions/slider/slider-sample-6/slider-sample-6.component.html
- src/app/interactions/slider/slider-sample-6/slider-sample-6.component.scss
- src/app/interactions/slider/slider-sample-6/slider-sample-6.component.ts
> docs(slider): adding new slider labels feature sample

- src/app/scheduling/datepicker/datepicker-sample-7/datepicker-sample-7.component.html
- src/app/scheduling/timepicker/timepicker-sample-6/timepicker-sample-6.component.html
This sample update is for igniteui-angular `8.0.0`
> chore(*): Drop down target update

- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.html
- src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
- src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.html
- src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.scss
- src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid.module.ts
Add paging styling samples for Hierarchical and TreeGrid
Closes #1192
> add paging style examples for grids

- src/app/grid-finjs/grid-finjs-demo.component.html
- src/app/grid-finjs/grid-finjs-demo.component.ts
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Fix filtering issue in FinJS demos

- src/app/grid/grid-contextmenu-sample/grid-contextmenu-sample.component.ts
> Get selected ranges after onRangeSelection event (7.3.x)

- src/app/grid-finjs/grid-finjs-demo.component.html
- src/app/grid-finjs/grid-finjs-demo.component.ts
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
Fixes issue on:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#live-updating-demo
> Fix the trend icon for grid finjs demo, debounce the slider value changed event

- src/app/grid/grid-contextmenu-sample/grid-contextmenu-sample.component.ts
> Get selected ranges after onRangeSelection event (master)

- src/app/grid-finjs/grid-finjs-demo.component.scss
> fix button icon style in FinjS demo

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/grid/grid-resize-line-styling-sample/grid-resize-line-styling-sample.html
- src/app/grid/grid-resize-line-styling-sample/grid-resize-line-styling-sample.scss
- src/app/grid/grid-resize-line-styling-sample/grid-resize-line-styling-sample.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
- src/app/hierarchical-grid/hierarchical-grid-resize-line-styling/hierarchical-grid-resize-line-styling.component.html
- src/app/hierarchical-grid/hierarchical-grid-resize-line-styling/hierarchical-grid-resize-line-styling.component.scss
- src/app/hierarchical-grid/hierarchical-grid-resize-line-styling/hierarchical-grid-resize-line-styling.component.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
- src/app/tree-grid/tree-grid-resize-line-styling-sample/tree-grid-resize-line-styling-sample.component.html
- src/app/tree-grid/tree-grid-resize-line-styling-sample/tree-grid-resize-line-styling-sample.component.scss
- src/app/tree-grid/tree-grid-resize-line-styling-sample/tree-grid-resize-line-styling-sample.component.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid.module.ts
Related to IgniteUI/igniteui-docfx#1275
> docs(grid): Added styling section in the resizing topics for grids

- src/app/theming/styles/theme-classes.scss
- src/app/theming/theme-chooser/theme-chooser-sample.component.html
- src/app/theming/theme-chooser/theme-chooser-sample.component.scss
- src/app/theming/theme-chooser/theme-chooser-sample.component.ts
- src/app/theming/theming.module.ts
> Adding IgxSelect for theme selection

- src/app/grid-finjs/grid-finjs-demo.component.html
- src/app/grid-finjs/grid-finjs-demo.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
> Diminish height for demos (7.3.x)

- live-editing/configs/ListConfigGenerator.ts
> Adding config for List theming sample

- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Fix filtering in the TreeGrid FinJS demo

- live-editing/generators/SharedAssetsGenerator.ts
- live-editing/templates/polyfills.ts.template
> Add polyfill template for IE

- src/app/notifications/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
- src/app/notifications/snackbar/snackbar-sample-4/snackbar-sample-4.component.scss
Closes #1239 
Fixing the visibility of an action button.
> Fixing the visibility of a button

- src/app/interactions/overlay/overlay-positioning-1/overlay-position-sample-1.component.scss
> Set igx-card height

- src/app/tree-grid/tree-grid-column-moving-styled-sample/tree-grid-column-moving-styled-sample.component.ts
> fix(tree-grid): fix renamed data source (#1268)

- src/app/grid-finjs/grid-finjs-demo.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
> Fixed shrinked menus above FinJS-Grid an FinJS-TreeGrid

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grid-toolbar-style/grid-toolbar-style.component.html
- src/app/grid/grid-toolbar-style/grid-toolbar-style.component.scss
- src/app/grid/grid-toolbar-style/grid-toolbar-style.component.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
- src/app/hierarchical-grid/hierarchical-grid-toolbar-style/hierarchical-grid-toolbar-style.component.html
- src/app/hierarchical-grid/hierarchical-grid-toolbar-style/hierarchical-grid-toolbar-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-toolbar-style/hierarchical-grid-toolbar-style.component.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid-toolbar-style/tree-grid-toolbar-style.component.html
- src/app/tree-grid/tree-grid-toolbar-style/tree-grid-toolbar-style.component.scss
- src/app/tree-grid/tree-grid-toolbar-style/tree-grid-toolbar-style.component.ts
- src/app/tree-grid/tree-grid.module.ts
> Add styling sample for toolbar

- src/app/layouts/tabbar/tabbar-sample-3/tabbar-sample-3.component.ts
- src/app/layouts/tabs/tabs-sample-6/tabs-sample-6.component.ts
> Fix navigation with URL select in the tabs routing samples

- live-editing/configs/TreeGridConfigGenerator.ts
> Fix TreeGrid batch editing stackblitz. #1313

- live-editing/configs/TreeGridConfigGenerator.ts
> Removed unneeded ToastModule from ngImports. #1323

- src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.ts
- src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.ts
- src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.ts
> Clear filtering on deleting input value in the template filter cell samples

- live-editing/configs/SparklineConfigGenerator.ts
- src/app/charts/charts-routes-data.ts
- src/app/charts/charts-routing.module.ts
- src/app/charts/sparkline/sparkline-grid/sparkline-grid.component.html
- src/app/charts/sparkline/sparkline-grid/sparkline-grid.component.scss
- src/app/charts/sparkline/sparkline-grid/sparkline-grid.component.ts
- src/app/charts/sparkline/sparkline-samples.module.ts
- src/app/utilities/Products.ts
added SparklineGrid sample per request from Jason
NOTE this PR should be reviewed/merged ASAP
> added SparklineGrid sample

- live-editing/configs/DialogConfigGenerator.ts
- src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.html
- src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.scss
- src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.ts
- src/app/interactions/interactions-routes-data.ts
- src/app/interactions/interactions-routing.module.ts
- src/app/interactions/interactions.module.ts
> Add dialog styling sample

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/grid/grid-filtering-style/grid-filtering-style.component.html
- src/app/grid/grid-filtering-style/grid-filtering-style.component.scss
- src/app/grid/grid-filtering-style/grid-filtering-style.component.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
- src/app/hierarchical-grid/hierarchical-grid-filtering-style/hierarchical-grid-filtering-style.component.html
- src/app/hierarchical-grid/hierarchical-grid-filtering-style/hierarchical-grid-filtering-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-filtering-style/hierarchical-grid-filtering-style.component.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
- src/app/tree-grid/tree-grid-filtering-style/tree-grid-filtering-style.component.html
- src/app/tree-grid/tree-grid-filtering-style/tree-grid-filtering-style.component.scss
- src/app/tree-grid/tree-grid-filtering-style/tree-grid-filtering-style.component.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid.module.ts
> Add filter row style samples

- live-editing/configs/CalendarConfigGenerator.ts
- src/app/scheduling/calendar/calendar-sample-1/calendar-sample-1.component.scss
- src/app/scheduling/calendar/calendar-sample-2/calendar-sample-2.component.scss
- src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.scss
- src/app/scheduling/calendar/calendar-sample-4/calendar-sample-4.component.scss
- src/app/scheduling/calendar/calendar-sample-5/calendar-sample-5.component.scss
- src/app/scheduling/calendar/calendar-sample-6/calendar-sample-6.component.scss
- src/app/scheduling/calendar/calendar-sample-7/calendar-sample-7.component.scss
- src/app/scheduling/calendar/calendar-styling-sample/calendar-styling-sample.component.html
- src/app/scheduling/calendar/calendar-styling-sample/calendar-styling-sample.component.scss
- src/app/scheduling/calendar/calendar-styling-sample/calendar-styling-sample.component.ts
- src/app/scheduling/calendar/calendar-views/calendar-views.component.html
- src/app/scheduling/calendar/calendar-views/calendar-views.component.scss
- src/app/scheduling/scheduling-routes-data.ts
- src/app/scheduling/scheduling-routing.module.ts
- src/app/scheduling/scheduling.module.ts
> Add calendar styling sample

- src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.html
- src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.ts
- src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.html
- src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.ts
- src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.html
- src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.ts
> Fix custom filter cell template samples

- live-editing/configs/HierarchicalGridConfigGenerator.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
- src/app/hierarchical-grid/hierarchical-grid-summary-styling/hierarchical-grid-summary-styling.component.html
- src/app/hierarchical-grid/hierarchical-grid-summary-styling/hierarchical-grid-summary-styling.component.scss
- src/app/hierarchical-grid/hierarchical-grid-summary-styling/hierarchical-grid-summary-styling.component.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
> Hierarchical grid summary styling sample

- package-lock.json
- package.json
Angular upgrade to version to 8.2.2
> Update igniteui for angular to 8.1.4

- live-editing/configs/GridCRMConfigGenerator.ts
- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/grid-crm/grid-crm.module.ts
- src/app/grid-crm/grid-crm/grid-crm.component.html
- src/app/grid-crm/grid-crm/grid-crm.component.ts
- src/app/grid/grid-boston-marathon/grid.component.html
- src/app/grid/grid-boston-marathon/grid.component.ts
- src/app/grid/grids.module.ts
- src/app/hierarchical-grid/hierarchical-grid-column-resizing/hierarchical-grid-resizing.component.html
- src/app/hierarchical-grid/hierarchical-grid-column-resizing/hierarchical-grid-resizing.component.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
- src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.html
- src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.ts
- src/app/tree-grid/tree-grid-primaryforeignkey-sample/tree-grid-primaryforeignkey-sample.component.html
- src/app/tree-grid/tree-grid-primaryforeignkey-sample/tree-grid-primaryforeignkey-sample.component.ts
- src/app/tree-grid/tree-grid.module.ts
> Add sparkline column to grid demos

- src/app/grid-finjs/grid-finjs-demo.component.html
- src/app/grid-finjs/grid-finjs-demo.component.scss
- src/app/grid-finjs/grid-finjs-demo.component.ts
- src/app/grid-finjs/grid-finjs.module.ts
> Adding category chart for FinJS demo (master)

- package-lock.json
- package.json
For the testing, run `npm run build` and `npm run start:live-editing`
> Update to 8.2.0-beta.5

- src/app/layouts/card/card-sample-2/card-sample-2.component.html
- src/app/layouts/card/card-sample-2/card-sample-2.component.scss
> fix(card): fix horizontal cad sample in IE11

- src/app/grid-finjs/grid-finjs-demo.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
- src/app/treegrid-finjs/treegrid-finjs.module.ts
> Add data chart to tree grid finjs

- live-editing/configs/GridFinjsConfigGenerator.ts
- live-editing/configs/TreeGridFinjsConfigGenerator.ts
- src/app/grid-finjs/grid-finjs-demo.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Adding missing modules and change set iteration approach

- package-lock.json
- package.json
Execute `npm run build` and `npm run start:live-editing`
> Update to beta.6

- src/app/data-entries/select/select-sample-2/select-sample-2.component.html
- src/app/data-entries/select/select-sample-2/select-sample-2.component.ts
> Simplify select groups demo

- web.config
> Update web.config #1502

- web.config
> Web config changes master

- src/app/grid/grid-save-state/grid-state.component.html
- src/app/grid/grid-save-state/state.directive.ts
IgniteUI/igniteui-angular#5842
> Fix grid persistence sample - vNext

- src/app/grid/grid-save-state/grid-state.component.html
- src/app/grid/grid-save-state/state.directive.ts
Closes IgniteUI/igniteui-angular#5842
> Fix grid persistence sample - master

- src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.html
- src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.ts
> Items in Kanban sample moved correctly

- live-editing/configs/TreeGridConfigGenerator.ts
> TreeGrid Row reordering demo has a missing file in StackBlitz - vNext

- live-editing/configs/TreeGridConfigGenerator.ts
> TreeGrid Row reordering demo has a missing file in StackBlitz - master

- live-editing/configs/TabBarConfigGenerator.ts
- src/app/layouts/layouts-routes-data.ts
- src/app/layouts/layouts-routing.module.ts
- src/app/layouts/layouts.module.ts
- src/app/layouts/tabbar/tabbar-style/tabbar-style.component.html
- src/app/layouts/tabbar/tabbar-style/tabbar-style.component.scss
- src/app/layouts/tabbar/tabbar-style/tabbar-style.component.ts
> Add bottomNav style sample - vNext

- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid-style/tree-grid-style.component.html
- src/app/tree-grid/tree-grid-style/tree-grid-style.component.scss
- src/app/tree-grid/tree-grid-style/tree-grid-style.component.ts
- src/app/tree-grid/tree-grid.module.ts
> Add tree grid style sample - vNext

- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid-style/tree-grid-style.component.html
- src/app/tree-grid/tree-grid-style/tree-grid-style.component.scss
- src/app/tree-grid/tree-grid-style/tree-grid-style.component.ts
- src/app/tree-grid/tree-grid.module.ts
> Add tree grid style sample - master

- src/app/layouts/carousel/carousel-details/carousel-details.component.ts
- src/app/layouts/carousel/carousel-sample-4/carousel-sample-4.component.ts
> Update carousel routing sample - vNext

- src/app/grid/grid-dynamic-chart-data/chart.service.ts
- src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.html
- src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.scss
- src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.ts
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
- src/app/grid/grid-dynamic-chart-data/initializers.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
- src/app/grid/services/financialData.ts
- src/styles.scss
> Adding grid with chart integration sample (vNext)

- src/app/grid/grid-dynamic-chart-data/chart.service.ts
- src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.html
- src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.scss
- src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.ts
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
- src/app/grid/grid-dynamic-chart-data/initializers.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
- src/app/grid/services/financialData.ts
- src/styles.scss
> Adding grid with chart integration sample (master)

- src/app/grid/grid-sample-3/grid-sample-3.component.html
> Adding date format for Grid Summary sample (vnext)

- src/app/grid/grid-sample-3/grid-sample-3.component.html
> Formatting date column for Grid Summary sample (master)

- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
> FIx paths for chart integration demo

- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
> Fix issue 1564 vnext

- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
Related to the following [comment](https://github.com/IgniteUI/igniteui-angular-samples/issues/1485#issuecomment-549754513)
> Fix issues for chart integration (master)

- src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.ts
Closes https://github.com/IgniteUI/igniteui-angular-samples/issues/1316
> Adding a fix for a not working clear button.

- src/app/grid/grid-editing-sample/grid-editing-sample.component.html
Fix for issue #1580 
Changing [valueKey] to [displayKey] for the combo editor.
> Fix(sample)#1580-Changing [valueKey] to [displayKey] for the combo editor.

- live-editing/configs/GridConfigGenerator.ts
> Fix Cell Selection sample stakcblitz config (master)

- package-lock.json
- src/app/grid-finjs/grid-finjs-demo.component.ts
- src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
Related to https://github.com/IgniteUI/igniteui-docfx/pull/1686
> Data analysis sample with perf impr

- src/app/theming/default-theme-sample/default-theme-sample.component.html
- src/app/theming/default-theme-sample/default-theme-sample.component.scss
Closes https://github.com/IgniteUI/igniteui-docfx/issues/1671
> leave the button exactly as how the default theme styles it

- src/app/grid/grid-master-detail/grid-master-detail.component.html
> Configure category chart's crosshair in master detail grid

- src/app/grid-crm/grid-crm/grid-crm.component.ts
> Prevent sparkline column to be exported in grid CRM (master)

- src/app/grid/grid-sample-4/grid-sample-4.component.scss
- src/app/grid/grid-sample-4/grid-sample-4.component.ts
> feat(remote-virtualization): add content placeholder animation

- projects/app-lob/src/app/grid/grid-master-detail/grid-master-detail.component.html
> Changing crosshair display mode

- src/app/grid/grid-editing-sample/grid-editing-sample.component.html
- src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
The issue is https://github.com/IgniteUI/igniteui-angular/issues/6365
> Synchronize grid outlet with templated editor outlet

- src/app/grid/grid-row-reorder-sample/grid-row-reorder.ts
- src/app/hierarchical-grid/hierarchical-grid-row-reorder/hierarchical-grid-row-reorder.component.ts
- src/app/tree-grid/tree-grid-row-reorder/tree-grid-row-reorder.component.ts
> fix(row-drag): fix row reorder `cursorPosition`

- live-editing/configs/ComboConfigGenerator.ts
- src/app/lists/combo/combo-single-selection/combo-single-selection.component.html
- src/app/lists/combo/combo-single-selection/combo-single-selection.component.scss
- src/app/lists/combo/combo-single-selection/combo-single-selection.component.ts
- src/app/lists/combo/combo-single-selection/local-data.ts
- src/app/lists/lists-routes-data.ts
- src/app/lists/lists-routing.module.ts
- src/app/lists/lists.module.ts
> Adding combo single selection sample master

- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.html
- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.scss
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- projects/app-lob/src/styles.scss
> Add dark Scrollbars and responsiveness changes

- src/app/grid-finjs/grid-finjs-demo.component.html
- src/app/grid-finjs/grid-finjs-demo.component.scss
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- src/styles.scss
> Add dark Scrollbars and responsiveness changes - master

- projects/app-lob/src/app/app.module.ts
- src/app/app.module.ts
> Add hammer module

- src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.scss
> fix(drag-drop): make kanban sample responsive #1709

- src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.html
- src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.scss
- src/app/hierarchical-grid/hierarchical-grid-row-drag-base/hierarchical-row-drag-base.component.html
- src/app/hierarchical-grid/hierarchical-grid-row-drag-base/hierarchical-row-drag-base.component.scss
- src/app/hierarchical-grid/hierarchical-grid-row-drag/hierarchical-grid-row-drag.component.html
- src/app/hierarchical-grid/hierarchical-grid-row-drag/hierarchical-grid-row-drag.component.scss
- src/app/hierarchical-grid/hierarchical-grid-row-reorder/hierarchical-grid-row-reorder.component.html
- src/app/hierarchical-grid/hierarchical-grid-row-reorder/hierarchical-grid-row-reorder.component.scss
> fix(row-drag): set the width of the row drag samples in percentages #1707

- src/app/interactions/drag-drop/list-reorder-sample/list-reorder-sample.component.html
> fix(sample): Fixing error in class binding.

- src/app/layouts/carousel/carousel-no-navigation-sample/carousel-no-navigation-sample.component.html
> Fix carousel sample

- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.html
- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.ts
- projects/app-lob/src/app/services/financialData.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Add "edit" feature to FinJS sample

- src/app/grid-finjs/grid-finjs-demo.component.html
- src/app/grid-finjs/grid-finjs-demo.component.ts
- src/app/grid/services/financialData.ts
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Add editable columns to FinJS demo

- src/app/hierarchical-grid/hierarchical-grid-collapsible-column-groups/hierarchical-grid-collapsible-column-groups.component.html
> fix(*): Changing field property in template to the right one

- src/app/hierarchical-grid/data.ts
> fix(*): Make sure that date property is set properly

- README.md
> Updating README (master)

- README.md
> Adding section for custom igniteui-angular builds inside igniteui-angular-samples (master)

- live-editing/configs/TreeGridConfigGenerator.ts
> Fix data path for Tree Grid clipboard operations sample vNext

- live-editing/configs/TreeGridConfigGenerator.ts
> Fix data path for Tree Grid clipboard operations sample master

- src/styles.scss
> Fix IE 11 styles problem vNext

- src/styles.scss
> Fix IE 11 styles issue (master) #1777

- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.scss
Closes #1756 
PR to vNext: #1785
> Fixes financial sample's slider labels' colors when a dark theme is applied

- src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.html
Closes: #1172 
Adding input type number inside the  [ Input Group Full-Form sample ](http://localhost:4200/samples/data-entries/input-group-sample-6)
> Adding input type number

- projects/app-lob/src/app/index/docs-layout.component.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/data-entries/input-group/base-input.component.ts
- src/app/data-entries/input-group/input-group-sample-1/input-group-sample-1.component.ts
- src/app/data-entries/input-group/input-group-sample-2/input-group-sample-2.component.ts
- src/app/data-entries/input-group/input-group-sample-3/input-group-sample-3.component.ts
- src/app/data-entries/input-group/input-group-sample-4/input-group-sample-4.component.ts
- src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.ts
- src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.ts
- src/app/services/global-input-type.service.ts
Closes #1757
Should be merged together with:
IgniteUI/igniteui-docfx-template#164
> chore(*): Adding logic to handle input type change if theme is changed.

- projects/app-lob/src/app/app.component.ts
Issue : Theming widget was not working locally with LOB application
> Fix app-lob project to work with local Taas

- live-editing/configs/DragAndDropConfigGenerator.ts
> fix(sample): Fixing stakblitz config for drag and drop samples.

- src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.ts
Fix for https://github.com/IgniteUI/igniteui-angular/issues/6678
> chore(*): Setting correct start index when remote filter is applied.

- src/app/layouts/card/card-styling-sample/card-styling-sample.component.html
- src/app/layouts/card/card-styling-sample/card-styling-sample.component.scss
- src/app/layouts/card/card-styling-sample/card-styling-sample.component.ts
Closes #1809
Closes #1770
IgniteUI/igniteui-docfx#1824
> refactor(card): change card styled sample

- live-editing/configs/AvatarConfigGenerator.ts
- src/app/layouts/avatar/avatar-sample-1/avatar-sample-1.component.html
- src/app/layouts/avatar/avatar-sample-1/avatar-sample-1.component.scss
- src/app/layouts/avatar/avatar-sample-1/avatar-sample-1.component.ts
- src/app/layouts/avatar/avatar-sample-2/avatar-sample-2.component.html
- src/app/layouts/avatar/avatar-sample-2/avatar-sample-2.component.scss
- src/app/layouts/avatar/avatar-sample-2/avatar-sample-2.component.ts
- src/app/layouts/avatar/avatar-sample-3/avatar-sample-3.component.html
- src/app/layouts/avatar/avatar-sample-3/avatar-sample-3.component.scss
- src/app/layouts/avatar/avatar-sample-4/avatar-sample-4.component.html
- src/app/layouts/avatar/avatar-sample-4/avatar-sample-4.component.scss
- src/app/layouts/avatar/avatar-sample-4/avatar-sample-4.component.ts
- src/app/layouts/avatar/avatar-styling/avatar-styling.component.html
- src/app/layouts/avatar/avatar-styling/avatar-styling.component.scss
- src/app/layouts/avatar/avatar-styling/avatar-styling.component.ts
- src/app/layouts/layouts-routes-data.ts
- src/app/layouts/layouts-routing.module.ts
- src/app/layouts/layouts.module.ts
- src/styles.scss
> Avatar samples refactoring

- src/app/hierarchical-grid/hierarchical-grid-custom-kb-navigation/hierarchical-grid-custom-kb-navigation-sample.component.ts
> Update hierarchical grid keyboard navigation sample

- angular.json
> Increase any component style maximum error

- projects/app-lob/src/index.html
- src/index.html
Closes https://github.com/IgniteUI/igniteui-docfx/issues/1783
> adding scrollbar class for samples

- angular.json
> Add AOT for line of business application

- src/app/notifications/toast/toast-sample-5/toast-sample-5.component.ts
> fix(toast): fix toast positioning sample bug

- live-editing/configs/GridConfigGenerator.ts
- src/app/grid/grid-sample-pinning/grid-pinning.component.html
- src/app/grid/grid-sample-pinning/grid-pinning.component.ts
- src/app/grid/services/svgIcons.ts
> Updating custom column pinning sample with correct pinning icon

- src/app/grid/column-selection-styles/column-selection-styles.component.html
- src/app/grid/column-selection-styles/column-selection-styles.component.scss
- src/app/hierarchical-grid/column-selection-styles/hierarchical-grid-column-selection-styles.component.scss
- src/app/tree-grid/column-selection-styles/tree-grid-column-selection-style.component.scss
> Updating column selection style samples

- src/app/grid/grid-save-state/grid-state.component.html
- src/app/grid/grid-save-state/grid-state.component.scss
> Improving Interactions in Grid State Sample - 9.1

- src/app/grid/grid-save-state/grid-state.component.html
- src/app/grid/grid-save-state/grid-state.component.scss
Closes: #1918
PR to vNext: #1919
> Improving Interactions in Grid State Sample

- src/app/data-entries/buttonGroup/button-group-sample-1/button-group-sample-1.component.html
- src/app/data-entries/buttonGroup/button-group-sample-1/button-group-sample-1.component.scss
- src/app/data-entries/buttonGroup/button-group-sample-1/button-group-sample-1.component.ts
- src/app/data-entries/buttonGroup/button-group-sample-2/button-group-sample-2.component.scss
- src/app/data-entries/buttonGroup/button-group-sample-3/button-group-sample-3.component.scss
- src/app/data-entries/buttonGroup/button-group-sample-5/button-group-sample-5.component.html
- src/app/data-entries/buttonGroup/button-group-style/button-group-style.component.html
- src/app/data-entries/buttonGroup/button-group-style/button-group-style.component.scss
- src/app/data-entries/buttonGroup/button-group-style/button-group-style.component.ts
> refactor(button-group): improve samples

- live-editing/configs/InputGroupConfigGenerator.ts
- src/app/data-entries/input-group/input-group-sample-1/input-group-sample-1.component.html
- src/app/data-entries/input-group/input-group-sample-1/input-group-sample-1.component.scss
- src/app/data-entries/input-group/input-group-sample-1/input-group-sample-1.component.ts
- src/app/data-entries/input-group/input-group-sample-2/input-group-sample-2.component.html
- src/app/data-entries/input-group/input-group-sample-2/input-group-sample-2.component.scss
- src/app/data-entries/input-group/input-group-sample-2/input-group-sample-2.component.ts
> refactor(label&input): refactor label&input samples

- package-lock.json
- package.json
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.ts
Closes #1962
@hanastasov keep in mind that the PRs should be tested when a new alpha is released with [this fix](https://github.com/IgniteUI/igniteui-angular/pull/7280)
> Update remote paging sample

- README.md
Add guidance about how to use `npm link` command to link custom `igniteui-angular` build to samples project
Closes #1968
> Add nmp link to README.md

- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
> Use reduce instead of flat operator

- projects/app-lob/src/styles.scss
- src/styles.scss
> Fix rendering issue in IE11 (master)

- projects/app-lob/src/app/grid/grid-master-detail/grid-master-detail.component.html
Workaround of the new known limitation of the `igxForOf` directive IgniteUI/igniteui-docfx#1940
> Adds fixed height to the MDV sample row detail template

- projects/app-lob/src/app/grid-crm/grid-crm/grid-crm/grid-crm.component.html
> Update CRM Grid width

- src/app/grid/grid-sample-3/grid-sample-3.component.html
- src/app/grid/grid-sample-3/grid-sample-3.component.scss
- src/app/grid/grid-sample-3/grid-sample-3.component.ts
> Fixing media queries in summary sample (master)

- src/app/grid/grid-clipboard-operations-sample/grid-clipboard-operations-sample.component.html
> Update clipboard sample

- src/app/grid/grid-clipboard-operations-sample/grid-clipboard-operations-sample.component.html
> Update clipboard sample- master

- src/app/grid/grid-multi-row-layout-configuration/grid-multi-row-layout-configuration.component.scss
> Fix border position for layout config sample.

- src/app/layouts/carousel/carousel.component.ts
Update images to be previewed in the carousel sample
> Update carousel images src

- src/app/layouts/carousel/carousel.component.ts
Update image src in the carousel base sample
> Update carousel images src - master

- src/app/grid/multi-column-headers/multi-column-headers.html
> Remove duplicate columns in MCH sample - master

- src/app/grid/multi-column-headers/multi-column-headers.html
> Remove duplicate columns in MCH sample

- src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.html
- src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.scss
- src/app/data-entries/dropdown/drop-down-virtual/drop-down-virtual.component.html
- src/app/data-entries/dropdown/drop-down-virtual/drop-down-virtual.component.scss
- src/app/data-entries/dropdown/drop-down-virtual/drop-down-virtual.component.ts
- src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.html
- src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.scss
- src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.ts
- src/app/data-entries/dropdown/dropdown-sample-1/dropdown-sample-1.component.html
- src/app/data-entries/dropdown/dropdown-sample-1/dropdown-sample-1.component.scss
- src/app/data-entries/dropdown/dropdown-sample-2/dropdown-sample-2.component.html
- src/app/data-entries/dropdown/dropdown-sample-2/dropdown-sample-2.component.scss
- src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.html
- src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.scss
- src/app/data-entries/dropdown/dropdown-sample-4/dropdown-sample-4.component.html
- src/app/data-entries/dropdown/dropdown-sample-4/dropdown-sample-4.component.scss
- src/app/data-entries/dropdown/dropdown-sample-5/dropdown-sample-5.component.html
- src/app/data-entries/dropdown/dropdown-sample-5/dropdown-sample-5.component.scss
- src/app/data-entries/dropdown/dropdown-styling/dropdown-styling.component.html
- src/app/data-entries/dropdown/dropdown-styling/dropdown-styling.component.scss
> refactor(drop-down): improve drop-down samples

- src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.html
- src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.scss
- src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.html
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.scss
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
- src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.html
- src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.scss
- src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
> Keyboard navigation enahncements

- src/app/grid/grid-moving-sample/grid-moving-sample.component.html
- src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
- src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.html
- src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.ts
> Fix(): error should not be thrown when load Column Moving Samples - master

- src/app/grid/grid-moving-sample/grid-moving-sample.component.html
- src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
- src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.html
- src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.ts
> Fix(): error should not be thrown when load  Column Moving Samples - vnext

- live-editing/configs/SnackbarConfigGenerator.ts
- live-editing/configs/ToastConfigGenerator.ts
- src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.html
- src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.scss
- src/app/notifications/toast/toast-sample-3/toast-sample-3.component.html
- src/app/notifications/toast/toast-sample-3/toast-sample-3.component.scss
> Toast and Snackbar updated samples

- live-editing/configs/SnackbarConfigGenerator.ts
- live-editing/configs/ToastConfigGenerator.ts
- package-lock.json
- package.json
- src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.html
- src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.scss
- src/app/notifications/toast/toast-sample-3/toast-sample-3.component.html
- src/app/notifications/toast/toast-sample-3/toast-sample-3.component.scss
> Toast and Snackbar updated samples - master

- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
- src/app/grid/grid-allData-summary/grid-allData-summary.component.ts
- src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.ts
- src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.ts
- src/app/grid/grid-groupby-summary-sample/grid-groupby-summary-sample.component.ts
- src/app/grid/grid-groupby-summary-styling-sample/grid-groupby-summary-styling-sample.component.ts
- src/app/grid/grid-sample-3/grid-sample-3.component.ts
- src/app/grid/grid-save-state/grid-state.component.ts
- src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.ts
- src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.ts
- src/app/hierarchical-grid/hierarchical-grid-save-state/hGrid-state.component.ts
- src/app/hierarchical-grid/hierarchical-grid-summary-styling/hierarchical-grid-summary-styling.component.ts
- src/app/hierarchical-grid/hierarchical-grid-summary/hierarchical-grid-summary.component.ts
- src/app/tree-grid/tree-grid-displaydensity-sample/tree-grid-displaydensity-sample.component.ts
- src/app/tree-grid/tree-grid-editing-sample/tree-grid-editing-sample.component.ts
- src/app/tree-grid/tree-grid-summary2-sample/tree-grid-summary2-sample.component.ts
- src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.ts
> Fix grid samples with custom summaries for codesandbox

- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
- src/app/grid/grid-allData-summary/grid-allData-summary.component.ts
- src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.ts
- src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.ts
- src/app/grid/grid-groupby-summary-sample/grid-groupby-summary-sample.component.ts
- src/app/grid/grid-groupby-summary-styling-sample/grid-groupby-summary-styling-sample.component.ts
- src/app/grid/grid-sample-3/grid-sample-3.component.ts
- src/app/grid/grid-save-state/grid-state.component.ts
- src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.ts
- src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.ts
- src/app/hierarchical-grid/hierarchical-grid-summary-styling/hierarchical-grid-summary-styling.component.ts
- src/app/hierarchical-grid/hierarchical-grid-summary/hierarchical-grid-summary.component.ts
- src/app/tree-grid/tree-grid-displaydensity-sample/tree-grid-displaydensity-sample.component.ts
- src/app/tree-grid/tree-grid-editing-sample/tree-grid-editing-sample.component.ts
- src/app/tree-grid/tree-grid-summary2-sample/tree-grid-summary2-sample.component.ts
- src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.ts
> Fix grid samples with custom summaries for codesandbox (master)

- src/app/scheduling/timepicker/timepicker-sample-4/timepicker-sample-4.component.html
- src/app/scheduling/timepicker/timepicker-sample-4/timepicker-sample-4.component.ts
Reworking a sample to better reflect the disabled time parts functionality.
> Reworking a sample to better reflect the disabled time parts functionality.

- live-editing/configs/NavbarConfigGenerator.ts
- src/app/menus/menus-routes-data.ts
- src/app/menus/menus-routing.module.ts
- src/app/menus/menus.module.ts
- src/app/menus/navbar/navbar-custom-title/navbar-custom-title.component.html
- src/app/menus/navbar/navbar-custom-title/navbar-custom-title.component.ts
Closes #2126 
Adding navbar custom title sample
> samples(navbar): Custom title sample #2126

- src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
- src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
> fix(kbnav-sample): remove expandable cell ref

- src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.html
- src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.scss
- src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.ts
> Add calendar events sample

- src/app/interactions/toggle/toggle.component.ts
Related to https://github.com/IgniteUI/igniteui-angular/issues/7697
> Add closeOnEsc to overlay settings in toggle sample

- src/app/menus/navbar/navbar-custom-title/navbar-custom-title.component.html
> samples(navbar): Removing the text from title #2126

- src/app/lists/combo/combo-features/combo-features.component.html
- src/app/lists/combo/combo-features/combo-features.component.ts
Added case-sensitive search to combo features sample
> Add case-sensitive search to combo features sample

- src/app/grid/grid-pager-sample/grid-pager-sample.component.html
- src/app/grid/grid-pager-sample/grid-pager-sample.component.ts
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
- src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.html
- src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.html
Related to #2055
This change also removes all `selectLabel` refs
> Update paging localization strings

- src/app/grid/grid-pager-sample/grid-pager-sample.component.html
- src/app/grid/grid-pager-sample/grid-pager-sample.component.ts
- src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
- src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.html
- src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.html
Related to #2055
This change also removes all selectLabel refs
> Add paging localization vnext master

- src/app/data-entries/buttons/buttons-display-density/buttons-display-density.component.html
> style(button): add fab btn in buttons display density sample

- src/app/data-entries/buttons/buttons-sample-6/buttons-sample-6.component.html
https://github.com/IgniteUI/igniteui-angular/pull/7889
https://github.com/IgniteUI/igniteui-docfx/pull/2129
> refactor(button): add extended FAB in a sample

- live-editing/configs/GridConfigGenerator.ts
- package-lock.json
- package.json
- src/app/data/utils.ts
- src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grid-sorting-indicators/grid-sorting-indicators.component.html
- src/app/grid/grid-sorting-indicators/grid-sorting-indicators.component.scss
- src/app/grid/grid-sorting-indicators/grid-sorting-indicators.component.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
> Update igniteui-angular to 10.1.0-alpha.4 and Add Grid  sorting indicators sample

- src/app/data-entries/buttons/buttons-display-density/buttons-display-density.component.html
- src/app/data-entries/buttons/buttons-display-density/buttons-display-density.component.scss
> style(button): add extended fab btn in the display density sample

- src/app/interactions/overlay/overlay-styling/overlay-styling.component.html
- src/app/interactions/overlay/overlay-styling/overlay-styling.component.scss
- src/app/interactions/overlay/overlay-styling/overlay-styling.component.ts
Closes #1816
Update the sample to show how to style the overlay component.
> Update the overlay styling sample

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- package-lock.json
- package.json
- src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
- src/app/grid/grid-external-outlet-sample/grid-external-outlet-sample.component.html
- src/app/grid/grid-external-outlet-sample/grid-external-outlet-sample.component.scss
- src/app/grid/grid-external-outlet-sample/grid-external-outlet-sample.component.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
- src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.html
- src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.scss
- src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
- src/app/menus/navbar/navbar-sample-2/navbar-sample-2.component.html
- src/app/tree-grid/tree-grid-external-outlet/tree-grid-external-outlet-sample.component.html
- src/app/tree-grid/tree-grid-external-outlet/tree-grid-external-outlet-sample.component.scss
- src/app/tree-grid/tree-grid-external-outlet/tree-grid-external-outlet-sample.component.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid.module.ts
> Add a sample for grid external outlet

- src/app/grid/grid-excel-style-filtering-sample-3/grid-excel-style-filtering-sample-3.component.html
- src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-3/hierarchical-grid-excel-style-filtering-sample-3.component.html
- src/app/tree-grid/tree-grid-excel-style-filtering-sample-3/tree-grid-excel-style-filtering-sample-3.component.html
> Update ESF templates samples

- live-editing/configs/GridConfigGenerator.ts
- src/app/grid/grid-nested-data-binding-2/data.ts
- src/app/grid/grid-nested-data-binding-2/grid-nested-data-bind2.html
- src/app/grid/grid-nested-data-binding-2/grid-nested-data-bind2.scss
- src/app/grid/grid-nested-data-binding-2/grid-nested-data-bind2.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
> Show off new way to bind complex data

- src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.html
- src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.html
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
- src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.html
- src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
> Use `activeNodeChange` for the KB navigation demo 

- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
> Fix theme name

- src/app/grid/grid-batch-editing/grid-batch-editing-sample.component.ts
- src/app/hierarchical-grid/hierarchical-grid-batch-editing/hierarchical-grid-batch-editing.component.ts
- src/app/tree-grid/tree-grid-batch-editing/tree-grid-batch-editing-sample.component.ts
> Invokes endEdit on undo transaction to exit grid edit mode

- live-editing/services/DependencyResolver.ts
> Add fixed version object for dep resolver

- src/app/grid/grid-nested-data-binding-2/grid-nested-data-bind2.scss
> Fix nested data sample

- src/app/grid/grid-save-state/grid-state.component.html
- src/app/grid/grid-save-state/grid-state.component.scss
- src/app/hierarchical-grid/hierarchical-grid-save-state/hGrid-state.component.html
- src/app/hierarchical-grid/hierarchical-grid-save-state/hGrid-state.component.scss
- src/app/tree-grid/tree-grid-save-state/tGrid-state.component.html
- src/app/tree-grid/tree-grid-save-state/tGrid-state.component.scss
> fix width on state samples

- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Fix: Date and string columns are not sorted when datasource is updated -vNext

- src/app/grid/grid-sample-5/grid-sample-5.component.ts
> Invoking change detection cycle on data fetch - Infinite scroll sample 10.1.x

- src/app/tree-grid/tree-grid-external-excel-style-filtering/tree-grid-external-excel-style-filtering.component.html
- src/app/tree-grid/tree-grid-external-excel-style-filtering/tree-grid-external-excel-style-filtering.component.ts
> Fix ExpressionChangedAfterItHasBeenCheckedError

- live-editing/configs/GridConfigGenerator.ts
- src/app/grid/grid-editing-sample/grid-editing-sample.component.html
- src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
- src/app/grid/grid-editing-sample/product.ts
> Enhance main editing sample --master

- src/app/scheduling/datepicker/datepicker-sample-3/datepicker-sample-3.component.html
> fix(datepicker): fix multiview sample to show 2 months

- package-lock.json
- package.json
- src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
- src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
> Remove the use of column.elementRef

- live-editing/configs/MaskConfigGenerator.ts
- src/app/data-display/mask/mask-sample-1/mask-sample-1.component.html
- src/app/data-display/mask/mask-sample-1/mask-sample-1.component.scss
- src/app/data-display/mask/mask-sample-1/mask-sample-1.component.ts
- src/app/data-display/mask/mask-sample-3/mask-sample-3.component.ts
- src/app/data-display/mask/mask-sample-4/mask-sample-4.component.html
- src/app/data-display/mask/mask-sample-4/mask-sample-4.component.ts
- src/app/data-display/mask/mask-sample-5/mask-sample-5.component.html
- src/app/data-display/mask/model/person.ts
> refactor(mask): improve mask samples

- src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.html
- src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.ts
> Add a sample how to use the newly implemented InputGroupToken

- src/app/scheduling/datepicker/datepicker-sample-3/datepicker-sample-3.component.html
Changing one of the date picker samples to reflect the new label implementation.
> Updating a sample to display the new label implementation, #8086

- src/app/layouts/avatar/avatar-sample-1/avatar-sample-1.component.html
- src/app/layouts/avatar/avatar-sample-2/avatar-sample-2.component.html
- src/app/layouts/avatar/avatar-sample-3/avatar-sample-3.component.html
- src/app/layouts/avatar/avatar-sample-4/avatar-sample-4.component.html
- src/app/layouts/avatar/avatar-styling/avatar-styling.component.html
Related issue: IgniteUI/igniteui-docfx/issues/2223
> style(avatar): add missing brackets

- package-lock.json
- package.json
- src/app/scheduling/calendar/calendar-sample-1/calendar-sample-1.component.html
- src/app/scheduling/datepicker/datepicker-sample-1/datepicker-sample-1.component.html
> ShowWeekNumbers - Update calendar and date picker samples

- projects/app-lob/src/app/grid-crm/grid-crm/grid-crm/grid-crm.component.ts
> fix(crm-grid): Update date format method

- src/app/grid/grid-external-outlet-sample/grid-external-outlet-sample.component.html
- src/app/grid/grid-external-outlet-sample/grid-external-outlet-sample.component.ts
- src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.html
- src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.ts
- src/app/tree-grid/tree-grid-external-outlet/tree-grid-external-outlet-sample.component.html
- src/app/tree-grid/tree-grid-external-outlet/tree-grid-external-outlet-sample.component.ts
> Use input binding instead of setting overlay outlet it in the code

- src/app/scheduling/timepicker/timepicker-sample-4/timepicker-sample-4.component.html
Changing a sample to represent the custom label implementation.
> Changing a sample to represent the custom label implementation, #6905

- projects/app-lob/src/app/grid-crm/grid-crm/grid-crm/grid-crm.component.ts
- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
- src/app/data-entries/dropdown/dropdown-sample-4/dropdown-sample-4.component.ts
- src/app/data-entries/select/select-sample-4/select-sample-4.component.ts
- src/app/interactions/overlay/overlay-main-2/overlay-main-sample-2.component.ts
- src/app/interactions/overlay/overlay-main-3/overlay-main-sample-3.component.ts
- src/app/interactions/overlay/overlay-positioning-1/overlay-position-sample-1.component.ts
- src/app/interactions/overlay/overlay-positioning-2/overlay-position-sample-2.component.ts
- src/app/interactions/overlay/overlay-positioning-3/overlay-position-sample-3.component.ts
- src/app/interactions/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.ts
- src/app/interactions/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.ts
- src/app/interactions/toggle/toggle.component.ts
- src/app/theming/dark-theme-sample/dark-theme-sample.component.ts
- src/app/theming/default-theme-sample/default-theme-sample.component.ts
Move targetSettings to overlaySettings
> Move target to overlay settings

- src/app/grid/grid-row-drag-base/grid-row-drag-base.component.html
> fix(grid): fix grid width

- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.html
> refactor(finjs)Remove template in date column#2255

- projects/app-lob/src/app/grid-crm/grid-crm/grid-crm/grid-crm.component.scss
> refactor(CRM grid):Fix responsiveness #2271

- src/app/grid/grid-action-strip/grid-action-strip-sample.html
- src/app/grid/grid-action-strip/grid-action-strip-sample.ts
- src/app/grid/grid-add-row-sample/grid-add-row-sample.component.html
- src/app/grid/grid-add-row-sample/grid-add-row-sample.component.ts
- src/app/grid/grid-row-pinning-drag/grid-row-pinning-drag.component.html
- src/app/grid/grid-row-pinning-drag/grid-row-pinning-drag.component.ts
- src/app/grid/grid-row-pinning-styling/grid-row-pinning-styling.component.html
- src/app/grid/grid-row-pinning-styling/grid-row-pinning-styling.component.ts
- src/app/grid/grid-row-pinning/grid-row-pinning.component.html
- src/app/grid/grid-row-pinning/grid-row-pinning.component.ts
- src/app/hierarchical-grid/hierarchical-grid-row-pinning-styling/hierarchical-grid-row-pinning-styling.component.html
- src/app/hierarchical-grid/hierarchical-grid-row-pinning-styling/hierarchical-grid-row-pinning-styling.component.ts
- src/app/hierarchical-grid/hierarchical-grid-row-pinning/hierarchical-grid-row-pinning.component.html
- src/app/hierarchical-grid/hierarchical-grid-row-pinning/hierarchical-grid-row-pinning.component.ts
- src/app/tree-grid/tree-grid-row-pinning-styling/tree-grid-row-pinning-styling.component.html
- src/app/tree-grid/tree-grid-row-pinning-styling/tree-grid-row-pinning-styling.component.ts
- src/app/tree-grid/tree-grid-row-pinning/tree-grid-row-pinning.component.html
- src/app/tree-grid/tree-grid-row-pinning/tree-grid-row-pinning.component.ts
Related issue: https://github.com/IgniteUI/igniteui-angular/issues/8282
> Change all samples that use mouse events to show/hide action strip

- src/app/grid/grid-custom-filtering/grid-custom-filtering.component.ts
- src/app/hierarchical-grid/hierarchical-grid-filtering/hierarchical-grid-custom-filtering.component.ts
- src/app/tree-grid/tree-grid-filtering-custom-sample/tree-grid-filtering-custom-sample.component.ts
> Fix icon name in custom filtering sample

- src/app/notifications/toast/toast-sample-1/toast-sample-1.component.ts
- src/app/notifications/toast/toast-sample-5/toast-sample-5.component.ts
- src/app/notifications/toast/toast-style/toast-style.component.ts
> fix(toast): changing position bug

- projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.ts
> Fixing grid finjs data update

- src/app/tree-grid/tree-grid-clipboard-operations-sample/tree-grid-clipboard-operations-sample.component.ts
> Fixing treegrid clipboard interactions errors

- src/app/tree-grid/tree-grid-clipboard-operations-sample/tree-grid-clipboard-operations-sample.component.ts
> Fixing tGrid clipboard sample

- src/app/grid/grid-excel-style-filtering-style/grid-excel-style-filtering-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.scss
- src/app/tree-grid/tree-grid-excel-style-filtering-style/tree-grid-excel-style-filtering-style.component.scss
> fix(styles): fixed ESF input text color on filtering styling demos

- src/app/grid/grid-filtering-style/grid-filtering-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-filtering-style/hierarchical-grid-filtering-style.component.scss
- src/app/tree-grid/tree-grid-filtering-style/tree-grid-filtering-style.component.scss
> fix(styles): fixed quick filter input text color on filtering styling demos - master

- src/app/grid/grid-excel-style-filtering-style/grid-excel-style-filtering-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.scss
- src/app/tree-grid/tree-grid-excel-style-filtering-style/tree-grid-excel-style-filtering-style.component.scss
> fix(styles): fixed ESF input text color on filtering styling demos - master

- src/app/lists/list/list-sample-7/list-sample-7.component.ts
> fix(list-sample): set keepItem to true for rightItem pan

- src/app/hierarchical-grid/data.ts
- src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.html
- src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.ts
- src/app/hierarchical-grid/hierarchical-grid-batch-editing/hierarchical-grid-batch-editing.component.ts
- src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.ts
- src/app/hierarchical-grid/models.ts
> Add ID field of SINGERS data so that there is no duplication in PK values

- src/app/directives/prevent-scroll.directive.ts
> fix(directive): prevent scroll directive now applied to grid tbody - vNext

- src/app/directives/prevent-scroll.directive.ts
> fix(directive): prevent scroll directive now applied to grid tbody - master

- angular.json
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
> fix(HGrid): Save State Sample Issue #2344

- live-editing/generators/SampleAssetsGenerator.ts
- live-editing/generators/misc/LiveEditingFile.ts
> Additional properties to every main component's live editing json

- src/app/grid/grid-conditional-row-selectors/grid-conditional-row-selectors-sample.component.html
- src/app/grid/grid-sample-selection-template-excel/grid-sample-selection-template-excel.component.html
> fix(grid): Removing the dataType. #2358

- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.html
- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.scss
- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
> update boston martahon sample

- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
> Dont show winner so early

- projects/app-crm/src/app/grid-crm/grid-crm.component.html
- projects/app-crm/src/app/grid-crm/grid-crm.component.scss
- projects/app-crm/src/index.html
> Fix fonts on the page, remove unused improts

- src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.html
- src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.scss
- src/app/grid/grid-toolbar-style/grid-toolbar-style.component.scss
> fix(toolbar): fix styling sample

- src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.html
- src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.scss
- src/app/grid/grid-toolbar-style/grid-toolbar-style.component.scss
> Update toolbar styling sample

- .github/workflows/build-app-crm.yml
- .github/workflows/build-app-lob.yml
- projects/app-crm/src/index.html
- projects/app-lob/src/index.html
Specify CI for app-crm and app-lob
> Specify CI for app-crm and app-lob

- live-editing/generators/SampleAssetsGenerator.ts
- live-editing/generators/misc/LiveEditingFile.ts
> Additional properties to every main component's le json (master)

- live-editing/configs/DropDownConfigGenerator.ts
- src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.html
- src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.scss
- src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.ts
Related to: IgniteUI/igniteui-angular/issues/8656
> refactor(drop-down): include prefix, suffix and divider sample

- live-editing/configs/RadioConfigGenerator.ts
- package-lock.json
- package.json
- src/app/data-entries/data-entries-routes-data.ts
- src/app/data-entries/data-entries-routing.module.ts
- src/app/data-entries/data-entries.module.ts
- src/app/data-entries/radio/radio-group-sample/radio-group-sample.component.html
- src/app/data-entries/radio/radio-group-sample/radio-group-sample.component.scss
- src/app/data-entries/radio/radio-group-vertical/radio-group-vertical.component.html
- src/app/data-entries/radio/radio-group-vertical/radio-group-vertical.component.scss
- src/app/data-entries/radio/radio-group-vertical/radio-group-vertical.component.ts
Related to: IgniteUI/igniteui-angular/issues/8713
> chore(radio-group): add vertical alignment sample

- projects/app-lob/src/app/app.component.ts
- projects/app-lob/src/app/seo.service.ts
> Add OG properties -vnext

- projects/app-lob/src/app/app.component.ts
- projects/app-lob/src/app/seo.service.ts
> Add OG properties -master

- live-editing/generators/SampleAssetsGenerator.ts
- live-editing/templates/app.module.ts.template
> Formatting  app.module.ts live editing output file 

- live-editing/generators/SampleAssetsGenerator.ts
- live-editing/templates/app.module.ts.template
> format app module ts file ngImports (live-editing master)

- projects/app-lob/src/app/grid-finjs/grid-finjs.component.scss
- projects/app-lob/src/app/grid-finjs/main.component.scss
- projects/app-lob/src/app/grid-finjs/main.component.ts
Fix:
1) FinJS sample has scroll on staging.
2) Disable chart button if no data is selected
> Fix heights on FinJS

- src/app/data-entries/input-group/reactive-forms/reactive-forms.component.ts
Related to https://github.com/IgniteUI/igniteui-docfx/issues/2058
> Substituting the FormControl() call with ["", Validators.required]

- src/app/data-entries/input-group/reactive-forms/reactive-forms.component.ts
Related to https://github.com/IgniteUI/igniteui-docfx/issues/2058
> Substituting the FormControl() call with ["", Validators.required],

- projects/app-lob/src/app/grid-finjs/main.component.html
- src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
- src/app/grid/grid-row-drag/planet/planet.component.scss
- src/app/hierarchical-grid/hierarchical-grid-batch-editing/hierarchical-grid-batch-editing.component.scss
- src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.scss
- src/app/interactions/dialog/dialog-sample-3/dialog-sample-3.component.html
- src/app/interactions/dialog/dialog-sample-3/dialog-sample-3.component.scss
- src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.scss
- src/app/theming/default-theme-sample/default-theme-sample.component.scss
- src/app/tree-grid/tree-grid-editing-sample/tree-grid-editing-sample.component.scss
related to: IgniteUI/igniteui-angular/issues/8785
update all samples that have custom dialog styling
> refactor(igx-dialog) samples

- projects/app-lob/src/app/grid-finjs/main.component.html
- projects/app-lob/src/app/grid-finjs/main.component.ts
> Fix applying dark theme on finjs sample

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/grid/grid-formatted-filtering-strategy/grid-formatted-filtering-strategy.component.html
- src/app/grid/grid-formatted-filtering-strategy/grid-formatted-filtering-strategy.component.scss
- src/app/grid/grid-formatted-filtering-strategy/grid-formatted-filtering-strategy.component.ts
- src/app/grid/grid-routes-data.ts
- src/app/grid/grids-routing.module.ts
- src/app/grid/grids.module.ts
- src/app/hierarchical-grid/hierarchical-grid-formatted-filtering-strategy/hierarchical-grid-formatted-filtering-strategy.component.html
- src/app/hierarchical-grid/hierarchical-grid-formatted-filtering-strategy/hierarchical-grid-formatted-filtering-strategy.component.scss
- src/app/hierarchical-grid/hierarchical-grid-formatted-filtering-strategy/hierarchical-grid-formatted-filtering-strategy.component.ts
- src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
- src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
- src/app/hierarchical-grid/hierarchical-grid.module.ts
- src/app/tree-grid/tree-grid-formatted-filtering-strategy/tree-grid-formatted-filtering-strategy.component.html
- src/app/tree-grid/tree-grid-formatted-filtering-strategy/tree-grid-formatted-filtering-strategy.component.scss
- src/app/tree-grid/tree-grid-formatted-filtering-strategy/tree-grid-formatted-filtering-strategy.component.ts
- src/app/tree-grid/tree-grid-routes-data.ts
- src/app/tree-grid/tree-grid-routing.module.ts
- src/app/tree-grid/tree-grid.module.ts
> Add Formatted Filtering Strategy Samples

- projects/app-lob/src/app/grid-finjs/grid-finjs.component.html
- projects/app-lob/src/app/grid-finjs/grid-finjs.component.ts
> Apply appropriate theme for finjs selects-vnext

- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Apply appropriate theme for tree-grid finjs selects-master

- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> Apply appropriate theme for tree-grid finjs selects-vnext

- live-editing/configs/TreeGridConfigGenerator.ts
> Fix errors in the Tree Grid cell selection sample - master - 1705

- package-lock.json
- package.json
- projects/app-lob/src/app/grid-finjs/controllers.component.ts
- projects/app-lob/src/app/grid-finjs/grid-finjs.component.html
- projects/app-lob/src/app/grid-finjs/grid-finjs.component.ts
- projects/app-lob/src/app/grid-finjs/localData.service.ts
- projects/app-lob/src/app/grid-finjs/main.component.scss
- projects/app-lob/src/app/grid-finjs/main.component.ts
> FinJS sample performance improvements

- live-editing/configs/CalendarConfigGenerator.ts
- src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.html
- src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.scss
- src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.ts
- src/app/scheduling/scheduling-routes-data.ts
- src/app/scheduling/scheduling-routing.module.ts
- src/app/scheduling/scheduling.module.ts
Related to #https://github.com/IgniteUI/igniteui-docfx/issues/2562
> Expose RTL support sample -vnext

- live-editing/configs/CalendarConfigGenerator.ts
- src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.html
- src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.scss
- src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.ts
- src/app/scheduling/scheduling-routes-data.ts
- src/app/scheduling/scheduling-routing.module.ts
- src/app/scheduling/scheduling.module.ts
Related to #IgniteUI/igniteui-docfx#2562
> Expose RTL support sample -master

- live-editing/configs/LocalizationConfigGenerator.ts
- package-lock.json
- package.json
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.html
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.scss
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
- src/app/services/services-routes-data.ts
- src/app/services/services-routing.module.ts
- src/app/services/services.module.ts
Related https://github.com/IgniteUI/igniteui-docfx/issues/2580
> Add i18n sample utilizing i18n package - localize app 

- live-editing/configs/LocalizationConfigGenerator.ts
- package-lock.json
- package.json
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.html
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.scss
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
- src/app/services/services-routes-data.ts
- src/app/services/services-routing.module.ts
- src/app/services/services.module.ts
Related IgniteUI/igniteui-docfx#2580
> Add i18n sample utilizing i18n package - localize app - 11.1.x

- live-editing/Routes.ts
- projects/app-lob/src/app/app-routing.module.ts
- projects/app-lob/src/app/index/index.component.ts
- src/app/app-routing.module.ts
Related to #IgniteUI/igniteui-docfx#2632
> Change finjs routes - master

- src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.ts
- src/app/grid/grid-editing-events/grid-editing-events.component.ts
- src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
- src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.ts
- src/app/layouts/expansion-panel/expansion-sample-2/expansion-sample-2.component.ts
- src/app/lists/combo/combo-remote/combo-remote.component.ts
- src/app/lists/combo/combo-styling/combo-styling.component.ts
- src/app/lists/list/list-sample-7/list-sample-7.component.ts
- src/app/lists/list/list-sample-8/list-sample-8.component.ts
- src/app/notifications/banner/banner-advanced-sample/banner-advanced-sample.component.ts
- src/app/notifications/banner/banner-styling/banner-styling.component.ts
- src/app/notifications/toast/toast-sample-1/toast-sample-1.component.html
- src/app/notifications/toast/toast-sample-1/toast-sample-1.component.ts
- src/app/notifications/toast/toast-sample-2/toast-sample-2.component.html
- src/app/notifications/toast/toast-sample-3/toast-sample-3.component.html
- src/app/notifications/toast/toast-sample-4/toast-sample-4.component.html
- src/app/notifications/toast/toast-sample-5/toast-sample-5.component.html
- src/app/notifications/toast/toast-sample-5/toast-sample-5.component.ts
- src/app/notifications/toast/toast-style/toast-style.component.html
- src/app/notifications/toast/toast-style/toast-style.component.ts
- src/app/scheduling/timepicker/timepicker-sample-4/timepicker-sample-4.component.ts
- src/app/tree-grid/tree-grid-editing-events/tree-grid-editing-events.component.ts
> fix(toast): update toast methods names

- live-editing/configs/app-dv-configs/DVGridConfig.ts
> Fix live editing for Live-data grid - vnext

- live-editing/configs/app-dv-configs/DVGridConfig.ts
- package.json
- projects/app-lob/src/app/grid-finjs/grid-finjs.component.ts
> Fix live editing for Live-data grid - master

- live-editing/configs/app-dv-configs/DVGridConfig.ts
- live-editing/configs/app-dv-configs/DVTreeGridConfig.ts
- package-lock.json
- package.json
there might be a problem with the dependency, not present in CSB
> Add live-editing capabilities and update to 11.1.4

- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.ts
> fix tree grid finjs sample aggregations

- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
- projects/app-lob/src/app/services/signal-r.service.ts
> FinJS sample with DockManager enhancements

- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
- projects/app-lob/src/app/services/signal-r.service.ts
> FinJS sample with DockManager enhancements --master

- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.html
- projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.scss
- projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-grouping.pipe.ts
- projects/app-lob/src/app/treegrid-finjs/treegrid-finjs.module.ts
> Tree grid finjs sample group by - master

- live-editing/configs/app-dv-configs/DVGridConfig.ts
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.module.ts
- projects/app-lob/src/app/services/financialData.ts
- projects/app-lob/src/app/services/signal-r.service.ts
- src/styles.scss
> FinJS with DockManager - Add missing files and styles

- live-editing/configs/app-dv-configs/DVGridConfig.ts
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.module.ts
- projects/app-lob/src/app/services/financialData.ts
- projects/app-lob/src/app/services/signal-r.service.ts
- src/styles.scss
> FinJS with DockManager - Add missing files and styles - мастер

- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
- src/styles.scss
> Change Dock Manager theme inclusion (vnext)

- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
- projects/app-lob/src/styles.scss
> Change Dock Manager theme inclusion (master)

- src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.html
- src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.scss
> fix(input-group): remove unnecessary calc

- live-editing/configs/app-dv-configs/DVTreeGridConfig.ts
> added missing files to tree grid finjs config - vNext

- live-editing/configs/LocalizationConfigGenerator.ts
> Add i18n package as a sample dependency - vNext

- live-editing/configs/LocalizationConfigGenerator.ts
> Add i18n package as a sample dependency  - master

- gulpfile.js
- package-lock.json
- package.json
> Updating live editing to 1.0.5

- src/app/grid/grid-column-data-types-sample/grid-column-data-types-sample.component.html
- src/app/grid/grid-column-data-types-sample/grid-column-data-types-sample.component.ts
> Update column type samples

- src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.html
- src/app/data-entries/input-group/reactive-forms/reactive-forms.component.html
- src/app/data-entries/input-group/reactive-forms/reactive-forms.component.ts
- src/app/scheduling/timepicker/timepicker-sample-5/timepicker-sample-5.component.html
- src/app/scheduling/timepicker/timepicker-sample-6/timepicker-sample-6.component.html
- src/app/scheduling/timepicker/timepicker-sample-6/timepicker-sample-6.component.ts
> Update date and time pickers samples

- src/app/grid/grid-advanced-filtering-style/grid-advanced-filtering-style.component.html
- src/app/grid/grid-advanced-filtering-style/grid-advanced-filtering-style.component.scss
- src/app/grid/grid-excel-style-filtering-style/grid-excel-style-filtering-style.component.scss
> refactor(filtering): update styling samples

- src/app/grid/grid-advanced-filtering-style/grid-advanced-filtering-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-advanced-filtering-style/hierarchical-grid-advanced-filtering-style.component.html
- src/app/hierarchical-grid/hierarchical-grid-advanced-filtering-style/hierarchical-grid-advanced-filtering-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.scss
- src/app/tree-grid/tree-grid-advanced-filtering-style/tree-grid-advanced-filtering-style.component.html
- src/app/tree-grid/tree-grid-advanced-filtering-style/tree-grid-advanced-filtering-style.component.scss
- src/app/tree-grid/tree-grid-excel-style-filtering-style/tree-grid-excel-style-filtering-style.component.scss
Closes #2622 
Applying the original fix (#2624) for Hierarchical and Tree grids.
> fix(Filtering): HGrid and TreeGrid styling demos

- src/app/interactions/tooltip/tooltip-rich/tooltip-rich.component.scss
> fix(Tooltip): Fixed backround image url.

- src/app/grid/grid-batchEditing-remotePaging/batch-editing-remote-paging.component.ts
> fix(samples): Commit grid transactions #2073

- package-lock.json
- package.json
> chore(*): Update dock manager to Beta3

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/tree-grid/tree-grid-save-state/data.ts
- src/app/tree-grid/tree-grid-save-state/tGrid-state.component.ts
> fix(live-editing): fixed configs and added data file

- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
> Fix dymanic-chart-data scrollbar - vnext

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/tree-grid/tree-grid-save-state/data.ts
- src/app/tree-grid/tree-grid-save-state/tGrid-state.component.ts
> fix(live-editing): fixed configs and added data file - master

- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
- projects/app-lob/src/app/grid-finjs/controllers.component.scss
- projects/app-lob/src/app/grid-finjs/main.component.html
- projects/app-lob/src/app/grid-finjs/main.component.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
> fix(scrollbar): wrong color in dark theme

- src/main.ts
> use eventCoalescing and ngZoneRun coalesing

- package-lock.json
- package.json
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
Use Hindi for custom obj sample, as Latin is unavailable in Angular framework for currencies and stuff in the sample.
> Use BG localization strings from i18n package. Use Hindi for custom i18n - vNext

- package-lock.json
- package.json
- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
Closes #2695
For this PR to pass, 1st a new ignite-angular-i18n package containing the 9 languages should be released.
Tested with a custom package from the following [PR](https://github.com/IgniteUI/igniteui-angular-i18n/pull/81)
> Update localize app sample

- projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
> fix(data-analysis): fix context button -vnext

- projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
> fix(data-analysis): fix context button -master

- src/app/hierarchical-grid/hierarchical-grid-excel-exporter/hierarchical-grid-excel-export.sample.html
- src/app/hierarchical-grid/hierarchical-grid-excel-exporter/hierarchical-grid-excel-export.sample.ts
- src/app/services/export-csv/csv-export-sample-1/csv-export-sample-1.component.html
- src/app/services/export-csv/csv-export-sample-1/csv-export-sample-1.component.ts
- src/app/services/export-csv/csv-export-tree-grid-sample/csv-export-tree-grid-sample.component.html
- src/app/services/export-csv/csv-export-tree-grid-sample/csv-export-tree-grid-sample.component.ts
- src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
- src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.ts
- src/app/services/export-excel/excel-export-tree-grid-sample/excel-export-tree-grid-sample.component.html
- src/app/services/export-excel/excel-export-tree-grid-sample/excel-export-tree-grid-sample.component.ts
> Use toolbar for exporting samples, instead of button

- package-lock.json
- package.json
- src/app/grid/grid-column-hiding-sample/grid-column-hiding-sample.component.html
- src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.html
- src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.ts
- src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-hiding.component.html
- src/app/tree-grid/tree-grid-column-hiding-sample/tree-grid-column-hiding-sample.component.html
> Updates based on property sheet, overlaySettings and additional context

- live-editing/configs/LocalizationConfigGenerator.ts
> Remove localization samples configs shorten path -master

- package-lock.json
- package.json
- src/_variables.scss
- src/app/data-display/icon/material-icons-extended/material-icons-extended.component.scss
Depends on https://github.com/IgniteUI/igniteui-angular/pull/9905
> live-editing(sass): fall back to libsass

- src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.html
Add row editing to i18n sample, so a language change on the row edit template buttons is visible as well.
Related:
https://github.com/IgniteUI/igniteui-angular/issues/9830
> Add row editing to i18n sample

- src/app/scheduling/daterangepicker/daterangepicker-mode/daterangepicker-mode.html
Related to https://github.com/IgniteUI/igniteui-docfx/pull/2921
> Update a sample to be in dialog mode

- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
> fix data files

- projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
> Fix context menu button -vnext

- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/tree-grid/tree-grid-keyboard-navigation/data.ts
- src/app/tree-grid/tree-grid-keyboard-navigation/tree-grid-keyboard-navigation-sample.component.ts
> fix(live-editing): fixed data import - vNext

- projects/app-lob/src/app/index/docs-layout.component.scss
- src/app/index/docs-layout.component.scss
> Fix colors for samples content and background in dark themes

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
> Add excel export service in live editing config for MCH export #2779

- projects/app-lob/src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.ts
Closes #2770 
Skip the performance column from exporting
> fix(treegrid): Don't export perform column #2770

- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
> Fix SignalR sample icons - vnext

- src/app/grid/grid-advanced-filtering-style/grid-advanced-filtering-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-advanced-filtering-style/hierarchical-grid-advanced-filtering-style.component.scss
- src/app/tree-grid/tree-grid-advanced-filtering-style/tree-grid-advanced-filtering-style.component.scss
> samples(grid): fix advanced filter header background

- src/app/data-display/igxFor/igxFor.component.html
- src/app/lists/list/list-sample-4/list-sample-4.component.html
- src/app/lists/list/list-sample-7/list-sample-7.component.html
- src/app/lists/list/list-sample-8/list-sample-8.component.html
- src/app/tree-grid/tree-grid-add-row-sample/tree-grid-add-row-sample.component.html
- src/app/tree-grid/tree-grid-editing-sample/tree-grid-editing-sample.component.html
- src/app/tree-grid/tree-grid-editing-style/tree-grid-editing-sample.component.html
- src/app/tree-grid/tree-grid-excel-style-filtering-load-on-demand/tree-grid-excel-style-filtering-load-on-demand.component.html
- src/app/tree-grid/tree-grid-remote-filtering-sample/tree-grid-remote-filtering-sample.component.html
> fix(list): change deprecated color property #2858

- src/app/interactions/tooltip/tooltip-rich/tooltip-rich.component.scss
> fix(tooltip): fixed background color - vNext

- src/app/menus/action-strip/action-strip-paragraph-menu/action-strip-paragraph-menu.component.html
- src/app/menus/action-strip/action-strip-paragraph-menu/action-strip-paragraph-menu.component.scss
> refactor(action-strip): fix menu sample styling

- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
- projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
- projects/app-lob/src/styles.scss
> fix(dock-manager): update logic for toggle dark theme

- src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.ts
> fix(esf): show missing columns in select #2879

- src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.ts
> fix(esf): show missing columns in select #2879 - master

- package-lock.json
- src/app/data-display/icon/icon-sample-3/icon-sample-3.component.html
- src/app/grid/grid-sample-3/grid-sample-3.component.html
- src/app/grid/grid-sample-right-pinning/grid-right-pinning.component.html
- src/app/hierarchical-grid/hierarchical-grid-sample-right-pinning/hierarchical-grid-right-pinning.component.html
- src/app/interactions/tooltip/tooltip-rich/tooltip-rich.component.html
- src/app/layouts/card/card-styling-sample/card-styling-sample.component.html
- src/app/notifications/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
- src/app/pagination/paginator/pagination-sample.component.html
- src/app/tree-grid/tree-grid-summary-sample/tree-grid-summary-sample.component.html
- src/app/tree-grid/tree-grid-summary-styling/tree-grid-summary-styling.component.html
> Add back style.color of icons

- src/app/menus/navbar/navbar-custom-title/navbar-custom-title.component.html
- src/app/menus/navbar/navbar-sample-1/navbar-sample-1.component.html
- src/app/menus/navbar/navbar-sample-2/navbar-sample-2.component.html
- src/app/menus/navbar/navbar-sample-2/navbar-sample-2.component.scss
- src/app/menus/navbar/navbar-sample-3/navbar-sample-3.component.html
- src/app/menus/navbar/navbar-style/navbar-style.component.html
- src/app/menus/navbar/navbar.component.html
> chore(navbar): update samples ot use icon buttons

- package-lock.json
- package.json
Related to https://github.com/IgniteUI/igniteui-live-editing/issues/19
> Update live editing package -vnext

- package-lock.json
- package.json
Related to https://github.com/IgniteUI/igniteui-live-editing/issues/19
> Update live editing package -master

- src/app/layouts/accordion/accordion-sample-1/accordion-sample-1.component.html
- src/app/layouts/accordion/accordion-sample-1/accordion-sample-1.component.scss
- src/app/layouts/accordion/accordion-sample-2/accordion-sample-2.component.html
- src/app/layouts/accordion/accordion-sample-2/accordion-sample-2.component.scss
- src/app/layouts/accordion/accordion-sample-3/accordion-sample-3.component.html
- src/app/layouts/accordion/accordion-sample-3/accordion-sample-3.component.scss
> Fix slight jump when opening a new panel

- package-lock.json
- package.json
> Update live-editing -vnext

- package-lock.json
- package.json
> Update live-editing -master

- live-editing/configs/HierarchicalGridConfigGenerator.ts
- src/app/data/hierarchical-data.ts
- src/app/grid/grid-save-state/about.component.html
- src/app/hierarchical-grid/column-group-selection/hierarchical-grid-column-group-selection.component.ts
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.html
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
- src/app/hierarchical-grid/hierarchical-grid-collapsible-column-groups/hierarchical-grid-collapsible-column-groups.component.ts
- src/app/hierarchical-grid/hierarchical-grid-column-moving-styled/hierarchical-grid-moving-styled.component.ts
- src/app/hierarchical-grid/hierarchical-grid-column-moving/hierarchical-grid-moving.component.ts
- src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-pinning.component.ts
- src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.ts
- src/app/hierarchical-grid/hierarchical-grid-display-density/hierarchical-grid-density.component.ts
- src/app/hierarchical-grid/hierarchical-grid-multi-cell-style/hierarchical-grid-multi-cell-style.component.ts
- src/app/hierarchical-grid/hierarchical-grid-multi-column-header-template/hierarchical-grid-multi-column-template.component.ts
- src/app/hierarchical-grid/hierarchical-grid-multi-column-headers-export/hierarchical-grid-multi-column-export.component.html
- src/app/hierarchical-grid/hierarchical-grid-multi-column-headers-styling/hierarchical-grid-multi-column-styling.component.ts
- src/app/hierarchical-grid/hierarchical-grid-multi-column-headers/hierarchical-grid-multi-column.component.ts
- src/app/hierarchical-grid/hierarchical-grid-save-state/about.component.html
- src/app/tree-grid/tree-grid-save-state/about.component.html
> Reverts hierarchical data where deleted

- live-editing/configs/TreeGridConfigGenerator.ts
> fix(tree-filter): add live editing config

- live-editing/configs/NavbarConfigGenerator.ts
> fix(navbar): add button module to imports - master

- live-editing/configs/TreeGridConfigGenerator.ts
> fix(tree-filter): add live editing config - master

- live-editing/configs/ComboConfigGenerator.ts
- live-editing/configs/app-dv-configs/DVHierarchicalGridConfig.ts
- package-lock.json
- package.json
> fix(): update live editing and fix sample configs

- live-editing/configs/ComboConfigGenerator.ts
Closes #https://github.com/IgniteUI/igniteui-live-editing/issues/24
> fix(): simple combo configs

- live-editing/configs/ComboConfigGenerator.ts
- live-editing/configs/app-dv-configs/DVHierarchicalGridConfig.ts
- package-lock.json
- package.json
Related to #2967
Closes #https://github.com/IgniteUI/igniteui-live-editing/issues/24
Closes #2955
> fix(): update live editing and fix sample configs - master

- src/app/grid/grid-groupby-custom-sample/grid-groupby-custom-sample.component.html
Ensure correct data type is set so that date column values are parsed to Date objects.
Closes #2948
> Fix issues with custom group by sample

- src/app/grid/grid-batch-editing/grid-batch-editing-sample.component.html
- src/app/grid/grid-batch-editing/grid-batch-editing-sample.component.ts
> Add delete row functionality for grid-batch-editing-sample

- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.html
- src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.scss
Related to https://github.com/IgniteUI/igniteui-docfx/issues/3166
> Increase sample height for hgrid keyboard nav.

- src/app/grid/grid-cellSelection-sample/grid-cellSelection.component.html
- src/app/grid/grid-cellSelection-sample/grid-cellSelection.component.scss
- src/app/grid/grid-sample-selection/grid-selection.component.html
- src/app/grid/grid-sample-selection/grid-selection.component.scss
- src/app/hierarchical-grid/hierarchical-grid-cellSelection-sample/hierarchical-grid-cellSelection.component.html
- src/app/hierarchical-grid/hierarchical-grid-cellSelection-sample/hierarchical-grid-cellSelection.component.scss
- src/app/hierarchical-grid/hierarchical-grid-cellSelection-sample/hierarchical-grid-cellSelection.component.ts
- src/app/hierarchical-grid/hierarchical-grid-selection/hierarchical-grid-selection.component.html
- src/app/hierarchical-grid/hierarchical-grid-selection/hierarchical-grid-selection.component.scss
- src/app/tree-grid/tree-grid-cellSelection-sample/tree-grid-cellSelection.component.html
- src/app/tree-grid/tree-grid-cellSelection-sample/tree-grid-cellSelection.component.scss
- src/app/tree-grid/tree-grid-selection-sample/tree-grid-selection-sample.component.html
- src/app/tree-grid/tree-grid-selection-sample/tree-grid-selection-sample.component.scss
> Show snackbar in selection samples

- package-lock.json
- package.json
> Update to latest 13.2.0-beta.0

- src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html
- src/app/grid/grid-sorting-sample/grid-sorting-sample.component.scss
- src/app/grid/grid-sorting-sample/grid-sorting-sample.component.ts
- src/app/tree-grid/tree-grid-sorting-sample/tree-grid-sorting-sample.component.html
- src/app/tree-grid/tree-grid-sorting-sample/tree-grid-sorting-sample.component.scss
- src/app/tree-grid/tree-grid-sorting-sample/tree-grid-sorting-sample.component.ts
> Add sorting options in grid/tree grid samples

- README.md
> Update README.md with status badges

- src/app/interactions/slider/slider-sample-1/slider-sample-1.component.html
- src/app/interactions/slider/slider-sample-4/slider-sample-4.component.html
- src/app/interactions/slider/slider-styling-sample/app-slider-styling.component.html
> fix(slider): update ngModel from input on blur #3036

- live-editing/configs/IconConfigGenerator.ts
Closes #https://github.com/IgniteUI/igniteui-docfx/issues/2954
> fix(icon): add missing httpClientModule

- live-editing/configs/GridConfigGenerator.ts
- package-lock.json
- package.json
> Update live-editing version and fix sample configs

- package-lock.json
- package.json
Closes #https://github.com/IgniteUI/igniteui-angular/issues/11996
> Update library version - master

- src/app/grid/grid-crud-sample/crud-sample.component.ts
> branch the logic inside rowEditDone

- src/app/grid/grid-crud-sample/crud-sample.component.ts
> branch the logic inside rowEdit event

- live-editing/configs/SliderConfigGenerator.ts
Update slider samples as part of: [#10805](https://github.com/IgniteUI/igniteui-angular/issues/10805)
> fix(slider): add import of hammer module for interactions to work properly - vNext

- live-editing/configs/SliderConfigGenerator.ts
Update slider samples as part of: [#10805](https://github.com/IgniteUI/igniteui-angular/issues/10805)
> fix(slider): add import of hammer module for interactions to work properly - master

- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.scss
> fix(boston-maraton): change winner text to be black

- projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.scss
> fix(boston-maraton): change winner text to be black - master

- src/app/pivot-grid/pivot-export/pivot-export.component.html
- src/app/pivot-grid/pivot-export/pivot-export.component.scss
- src/app/pivot-grid/pivot-export/pivot-export.component.ts
Closes https://github.com/IgniteUI/igniteui-docfx/issues/3342
> feat(pivot-grid): export sample improvements - vNext

- src/app/scheduling/monthpicker/monthpicker-sample-3/monthpicker-sample-3.component.ts
> fix(localization): Fix localization in monthpicker sample

- src/app/lists/combo/simple-combo-cascading/simple-combo-cascading.component.html
- src/app/lists/combo/simple-combo-cascading/simple-combo-cascading.component.ts
- src/app/lists/lists.module.ts
> Add loading indicator for cascading simple combo sample vNext

- src/app/lists/combo/simple-combo-cascading/simple-combo-cascading.component.html
- src/app/lists/combo/simple-combo-cascading/simple-combo-cascading.component.ts
- src/app/lists/lists.module.ts
> Add loading indicator for cascading simple combo sample master

- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
- src/app/grid/grid-sample-pinning/grid-pinning.component.html
- src/app/grid/grid-sample-pinning/grid-pinning.component.scss
- src/app/grid/grid-sample-pinning/grid-pinning.component.ts
- src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-pinning.component.html
- src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-pinning.component.scss
- src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-pinning.component.ts
- src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-column-pinning-sample.component.html
- src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-column-pinning-sample.component.scss
- src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-column-pinning-sample.component.ts
> fix(grids): improve the appearance of the pinning icon in the Custom Column Pinning UI samples - vNext

- projects/app-lob/src/app/grid-finjs/controllers.component.html
- projects/app-lob/src/app/grid-finjs/controllers.component.ts
- projects/app-lob/src/app/grid-finjs/main.component.html
- projects/app-lob/src/app/grid-finjs/main.component.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
- src/styles.scss
Reverts IgniteUI/igniteui-angular-samples#3150
> Revert "removing the dark theme switch"

- projects/app-lob/src/app/grid-finjs/controllers.component.html
- projects/app-lob/src/app/grid-finjs/controllers.component.ts
- projects/app-lob/src/app/grid-finjs/main.component.html
- projects/app-lob/src/app/grid-finjs/main.component.ts
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
- projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
- projects/app-lob/src/styles.scss
> fix(finjs): add option to hide theme switch for sample

- projects/app-lob/src/app/grid-finjs/controllers.component.html
- projects/app-lob/src/app/grid-finjs/controllers.component.ts
> fix(finjs): add option to hide theme widget

- src/app/data/product.ts
> Change img url in the main-pagination sample data_vNext

- live-editing/configs/RadioConfigGenerator.ts
> Fix typo in radio group live editing config

- .browserslistrc
Closes [#3460](https://github.com/IgniteUI/igniteui-docfx/issues/3460)
> Add support for the last 2 major versions of Safari

- projects/app-crm/src/app/grid-crm/grid-crm.component.html
- projects/app-crm/src/app/grid-crm/grid-crm.component.scss
- Height adjustments
- Padding adjustments
> Grid CRM layout styling adjustments

- src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.html
> fix(grid styling): add height 100%

- src/app/data-entries/select/select-input-directives/select-input-directives.scss
- src/app/data-entries/select/select-sample-2/select-sample-2.component.scss
- src/app/grid/grid-column-data-types-sample/grid-column-data-types-sample.component.scss
The select component look is updated with a bigger button, so several samples seem off and need at least a width adjustment.
> Adjust select samples to the new styling

- projects/app-crm/src/app/grid-crm/grid-crm.component.html
- projects/app-crm/src/app/grid-crm/grid-crm.component.scss
> fix searchbar in crm sample

- src/app/tree-grid/tree-grid-rowStyles-sample/tree-grid-rowStyle.component.ts
> fix(tree-grid-rowStyles): reference RowType data properly

- package.json
Closes https://github.com/IgniteUI/igniteui-live-editing-samples/issues/7
> Live editing version upgrade

- src/app/grid/grid-sorting-sample/grid-sorting-sample.component.ts
- src/app/tree-grid/tree-grid-sorting-sample/tree-grid-sorting-sample.component.ts
> fix(sorting): initial sort in AfterViewInit

- src/app/scheduling/datepicker/datepicker-styling-sample/datepicker-styling-sample.component.scss
> fix(date-picker-styling-sample): add ng-deep selector to apply custom theme

- package-lock.json
- package.json
Related to #https://github.com/IgniteUI/igniteui-docfx-template/issues/442
> chore(*): Update live-editing with codesandbox setup configs

- gulpfile.js
Related to #https://github.com/IgniteUI/igniteui-docfx-template/issues/442
> chore(*): create submodule csb config folder

- gulpfile.js
- package-lock.json
- package.json
Related to #https://github.com/IgniteUI/igniteui-docfx-template/issues/442
> chore(*): Update codesandbox config

- live-editing/configs/GridConfigGenerator.ts
> IgxGrid custom group by sample, fix imports

- package-lock.json
- package.json
> chore(*): update live-editing version

- live-editing/configs/BannerConfigGenerator.ts
> fix(banner): delete duplicates ng imports

- src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.ts
- src/app/tree-grid/tree-grid-toolbar-sample-2/tree-grid-toolbar-sample-2.component.ts
Closes [#IgniteUI/igniteui-docfx/issues/2590](https://github.com/IgniteUI/igniteui-docfx/issues/2590)
> fix(tree-grid, toolbar): changing fileName to be the same as the code snippet

- live-editing/configs/BadgeConfigGenerator.ts
- src/app/data-display/badge/badge-icon/badge-icon.component.html
- src/app/data-display/badge/badge-icon/badge-icon.component.scss
- src/app/data-display/badge/badge-icon/badge-icon.component.ts
- src/app/data-display/data-display-routes-data.ts
- src/app/data-display/data-display-routing.module.ts
- src/app/data-display/data-display.module.ts
Related to IgniteUI/igniteui-angular/issues/13174
> feat(badge): material extended icons sample

- live-editing/configs/GridConfigGenerator.ts
> Adding missing IgxButtonModule

- src/app/grid/grid-column-hiding-toolbar-style/grid-column-hiding-toolbar-style.component.html
- src/app/grid/grid-column-hiding-toolbar-style/grid-column-hiding-toolbar-style.component.scss
Resolves https://github.com/IgniteUI/igniteui-angular-samples/issues/3301
> Fix column hiding style sample not using column actions. Fix styling not applying.

- src/app/grid/grid-advanced-filtering-style/grid-advanced-filtering-style.component.scss
> style(advanced-filtering-dialog): refactor styling

- src/app/menus/navdrawer/nav-drawer-styling/nav-drawer-styling.component.scss
> fix(nav-drawer): add ng-deep selector to apply custom theme

- src/app/grid/grid-conditional-row-selectors/grid-conditional-row-selectors-sample.component.html
- src/app/grid/grid-conditional-row-selectors/grid-conditional-row-selectors-sample.component.ts
- src/app/hierarchical-grid/hierarchical-grid-conditional-row-selectors/hierarchical-grid-conditional-row-selectors.component.html
- src/app/hierarchical-grid/hierarchical-grid-conditional-row-selectors/hierarchical-grid-conditional-row-selectors.component.ts
- src/app/tree-grid/tree-grid-conditional-row-selectors/tree-grid-conditional-row-selectors.component.html
- src/app/tree-grid/tree-grid-conditional-row-selectors/tree-grid-conditional-row-selectors.component.ts
> fix(grids): Alter conditional row selection samples according to changed API

- projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.html
- projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.module.ts
> chore(*): include extras functionality in analysis sample

- live-editing/configs/GridConfigGenerator.ts
> fix(grid-sorting): add IgxButtonModule

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
> fix(esf-template): add IgxIconModule

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
> Add missing button import in grids save state samples

- package-lock.json
- package.json
Related to # https://github.com/IgniteUI/igniteui-live-editing/issues/40
> chore(*): update live editing version

- src/app/grid/grid-editing-excel-style/grid-editing-excel-style.component.ts
> fix(grid): refactor excel style editing sample

- src/app/grid/grid-editing-excel-style/grid-editing-excel-style.component.ts
> fix(grid): remove crud service from excel style editing sample

- live-editing/configs/TreeConfigGenerator.ts
Closes #https://github.com/IgniteUI/igniteui-docfx/issues/3672
> fix(tree config generator): remove redundant ivy flags

- live-editing/configs/GridConfigGenerator.ts
- live-editing/configs/HierarchicalGridConfigGenerator.ts
- live-editing/configs/TreeGridConfigGenerator.ts
> Add missing imports in grids Conditional Styling samples

- package-lock.json
- package.json
- src/app/layouts/carousel/carousel-with-components-sample/carousel-with-components-sample.component.scss
- src/app/layouts/carousel/carousel.component.scss
- src/app/theming/animations/animations-sample-2/animations-sample-2.component.html
- src/app/theming/shadows/card-sample-shadow/card-sample-shadow.html
Related to IgniteUI/igniteui-angular/pull/13948
> fix(samples): changes after indigo updates

- src/app/scheduling/calendar/calendar-days-view/calendar-days-view.component.scss
- src/app/scheduling/calendar/calendar-months-view/calendar-months-view.component.scss
- src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.scss
- src/app/scheduling/calendar/calendar-sample-1/calendar-sample-1.component.scss
- src/app/scheduling/calendar/calendar-sample-2/calendar-sample-2.component.scss
- src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.html
- src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.scss
- src/app/scheduling/calendar/calendar-sample-4/calendar-sample-4.component.scss
- src/app/scheduling/calendar/calendar-sample-5/calendar-sample-5.component.scss
- src/app/scheduling/calendar/calendar-sample-6/calendar-sample-6.component.scss
- src/app/scheduling/calendar/calendar-sample-7/calendar-sample-7.component.scss
- src/app/scheduling/calendar/calendar-sample-8/calendar-sample-8.component.scss
- src/app/scheduling/calendar/calendar-styling-sample/calendar-styling-sample.component.scss
- src/app/scheduling/calendar/calendar-years-view/calendar-years-view.component.scss
- src/app/scheduling/calendar/multiview/multiview.component.scss
- src/app/scheduling/monthpicker/monthpicker-sample-1/monthpicker-sample-1.component.scss
- src/app/scheduling/monthpicker/monthpicker-sample-3/monthpicker-sample-3.component.scss
- src/app/scheduling/monthpicker/monthpicker-styling/monthpicker-styling.component.scss
> fix calendar samples

- src/app/grid/custom-grid-paging-style/custom-grid-paging-style.component.scss
- src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.scss
- src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.scss
> Grid - fix paging style samples

- src/app/data/singersData.ts
> Fixed sample data issue #3487

- src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.ts
> FIxed TreeGrid sample row deletion

- src/app/tree-grid/tree-grid-tree-filter-view/tree-grid-tree-filter-view.component.html
- src/app/tree-grid/tree-grid-tree-filter-view/tree-grid-tree-filter-view.component.scss
- src/app/tree-grid/tree-grid-tree-filter-view/tree-grid-tree-filter-view.component.ts
> Fixing Tree Grid Filter View Sample 

- src/app/pivot-grid/pivot-grid-routes-data.ts
- src/app/pivot-grid/pivot-grids-routing.module.ts
- src/app/pivot-grid/pivot-grids.module.ts
- src/app/pivot-grid/pivot-layout/pivot-layout.component.html
- src/app/pivot-grid/pivot-layout/pivot-layout.component.scss
- src/app/pivot-grid/pivot-layout/pivot-layout.component.ts
layout sample with Horizontal UI settings
> docs(pivotGrid): added layout sample

- src/app/pivot-grid/pivot-grids.module.ts
- src/app/tree-grid/tree-grid-save-state/about.component.html
> docs(tGrid): fixed about page routing

- live-editing/configs/ComboConfigGenerator.ts
- src/app/lists/combo/simple-combo-cascading/simple-combo-cascading.component.ts
- src/app/lists/lists.module.ts
> fix(simple-combo): correct cascading sample clear buttons behavior

- src/app/grid/grid-external-advanced-filtering/grid-external-advanced-filtering.component.scss
- src/app/hierarchical-grid/hierarchical-grid-external-advanced-filtering/hierarchical-grid-external-advanced-filtering.component.scss
- src/app/tree-grid/tree-grid-external-advanced-filtering/tree-grid-external-advanced-filtering.component.scss
> fix(advance-filtering): ensure external filter remains fully visible

- src/app/interactions/query-builder/query-builder-sample-1/query-builder-sample-1.component.html
- src/app/interactions/query-builder/query-builder-sample-1/query-builder-sample-1.component.ts
Reverts IgniteUI/igniteui-angular-samples#3532
> Revert "refactor(query-builder-sample): update QB sample 1 with nested entities"

- src/app/grid/grid-cascading-combos/grid-cascading-combos.component.html
> Cascading combos sample: set overlaySettings.outlet element to the grid outlet

- src/app/grid/grid-allData-summary/grid-allData-summary.component.ts
- src/app/grid/grid-summary-template/grid-summary-template.component.ts
> fix(summary): correct typos in custom summaries samples

- projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
- projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
- projects/app-lob/src/app/services/floating-panes.service.ts
> chore(*): add missing extras directive imports

- package-lock.json
- package.json
> chore(*): update extras version

- projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
> chore(*): restore data analytics ng imports

- package-lock.json
- package.json
> chore(*): update extras package version

- src/app/grid/grid-custom-filtering/grid-custom-filtering.component.ts
- src/app/hierarchical-grid/hierarchical-grid-filtering/hierarchical-grid-custom-filtering.component.ts
- src/app/tree-grid/tree-grid-filtering-custom-sample/tree-grid-filtering-custom-sample.component.ts
> fix(grid): rename iconNames in custom filtering operands demos

- src/app/services/transaction/transaction-base/transaction-base.component.ts
> fix(transaction): add IgxTransactionService provider in the Transaction demo

- src/app/grid/grid-groupby-summary-styling-sample/grid-groupby-summary-styling-sample.component.scss
- src/app/hierarchical-grid/hierarchical-grid-summary-styling/hierarchical-grid-summary-styling.component.scss
Related to https://github.com/IgniteUI/igniteui-angular/issues/15477
> refactor(grid-samples): update grid summary styling samples

- src/app/lists/list/list-item-selection/list-item-selection.component.html
- src/app/lists/list/list-item-selection/list-item-selection.component.scss
- src/app/lists/list/list-item-selection/list-item-selection.component.ts
Same changes as master PR - #3646
> feat(list): add the new "selected" property to samples (vnext)

- src/app/theming/shadows/card-sample-shadow/card-sample-shadow.html
Related to https://github.com/IgniteUI/igniteui-angular/pull/15698
> refactor(card): remove old classes

- src/app/interactions/query-builder/query-builder-request-sample/query-builder-request-sample.component.ts
- src/app/interactions/query-builder/query-builder-sql-sample/query-builder-sql-sample.component.ts
> Update query builder samples on production

- angular.json
- src/app/app.routes.server.ts
Reverts IgniteUI/igniteui-angular-samples#3700
> Revert "feat(*): Enable SSR for the projects"

- src/app/grid/grid-sample-pinning-styling/grid-pinning-styling.component.ts
> fix(grid-pinning): custom pin icon not showing in styling sample

- src/app/grid/grid-multi-row-layout-configuration/grid-multi-row-layout-configuration.component.html
- src/app/grid/grid-multi-row-layout-configuration/grid-multi-row-layout-configuration.component.scss
> fix(mrl layout sample): fix chip and input group styles.
